### ISSUE TITLE
"runtime" and "meta" should be keywords in syntax highlighters

### ISSUE THREAD

**Issue by tmdefreitas** [openwdl/wdl#11]
runtime should be treated the same as "command" or "output"

Example:

`runtime { docker: "broadinstitute/picard"}`

**Comment by tmdefreitas** [comment]
Edit: "meta" is also listed as a keword

**Comment by scottfrazer** [comment]
Do you mean in the documentation/spec or with the Python parser?

**Comment by tmdefreitas** [comment]
![screen shot 2015-10-01 at 10 34 15 am](https://cloud.githubusercontent.com/assets/3845738/10223623/fd4e1ba4-6827-11e5-8303-22a367cd40b4.png)

I think this is part of the parser, I'm just suggesting that the meta tags and runtime tags have the same syntax highlighting

**Comment by scottfrazer** [comment]
Gotcha, so it's an issue with the Sublime/Textmate syntax highlighter.

**Comment by tmdefreitas** [comment]
More of a feature request, yes, consider it very low priority ;)

**Comment by geoffjentry** [comment]
Closing this as this is a spec repository and will ultimately be handled by other systems
