### ISSUE TITLE
Float => Int Coercion

### ISSUE THREAD

**Issue by jsotobroad** [openwdl/wdl#110]
It seems like this should be possible but it currently isn't (from what I can tell).

**Comment by jsotobroad** [comment]
Currently there is no nice way in wdl to convert from a `Float` to an `Int`.  As Jeff said things like `floor`, `ceil` and `round` (or whatever) would be handy as standard functions.

**Comment by patmagee** [comment]
Closing this, since `Floor` and `Ceil` functions have been added to `Draft 2 specification`
