### ISSUE TITLE
clarify refering outputs inside and outside scatter

### ISSUE THREAD

**Issue by antonkulaga** [openwdl/wdl#112]
It looks like output of the tasks work in different way depending on if you call it inside scatter (like with dec, where I get integer from inc.increment) or outside of scatter block (in such case I get array from inc.increment)
```
workflow wf {
  Array[Int] integers = [1,2,3,4,5]
  scatter (i in integers) {
    call inc {input: i=i}
    call dec {input: i=inc.increment} #inc.increment is integer
  }
  call sum {input: ints = inc.increment}  #inc.increment is an array
}
```
This is very confusing. Maybe it is possible to clarify the behaviour in docs?

**Comment by patmagee** [comment]
it looks like this was defined in the specification https://github.com/openwdl/wdl/blob/master/versions/draft-2/SPEC.md#scatter--gather
