### ISSUE TITLE
A contains style function for Array

### ISSUE THREAD

**Issue by ruchim** [openwdl/wdl#117]
This [WDL forum post](http://gatkforums.broadinstitute.org/wdl/discussion/9734/check-is-string-value-is-in-array-string#latest ) presents a use-case for why a contains style function on arrays could be very useful. It also reflects on the downsides of current workarounds in WDL.

It would be helpful to have a function called "contains" or "exists" which returns a Boolean depending on whether a given value exists/is contained within a given array.

Draft implementation: https://github.com/openwdl/wdl/tree/117-contains

**Comment by jdidion** [comment]
Restricting the allowed arguments to primitive types would help to avoid costly searches of nested collections.

## Proposed signatures:

`Boolean contains(Array[P], P)`
`Boolean contains(Array[P?], (P | None))`

**Comment by jdidion** [comment]
@patmagee grabbing this one from you
