### ISSUE TITLE
Import public WDL scripts from HCA

### ISSUE THREAD

**Issue by sooheelee** [openwdl/wdl#126]
At the Mint meeting heard these will all be public in the HCA repo (Skylab repo) and available to anyone to take. These would relate to single-cell RNA-Seq. Contacts are Mint team.

E.g. 10X pipeline WDL

At the least, point users to the repo in our README.

**Comment by geoffjentry** [comment]
This issue probably belongs somewhere, but that where is no longer here. @vdauwera - we're eventually making a repo for things like the GATK WDLs that are housed here, right?

**Comment by vdauwera** [comment]
Right, the GATK workflows are being moved to a separate org that serves as umbrella for multiple repos here: https://github.com/gatk-workflows. The contents will further be registered in places like Dockstore and Agora (FireCloud), which will serve as points of content aggregation.

We'll encourage other groups including Mint Team to do the same.
