### ISSUE TITLE
Consider Supporting Size() engine function for Complex Types

### ISSUE THREAD

**Issue by patmagee** [openwdl/wdl#129]
Dynamically sizing HDD & SDD sizes is a great feature about WDL + Cromwell that gives you cost savings in certain cloud environments. A current limitation is that you cannot call `size` on an `Array[File]` type or `Array[Array[....[File]..]]` Types, which forces you to either guess the required disk size, or build logic into your workflow upstream for determining file sizes. 

Some practical considerations:
- Arrays can have an arbitrary size causing a large number of calls to an engine function / API
- Would an Iterator function be a more generalizable solution?
- Would we restrict this to Arrays or should it be callable on all `File` Types, ie `Map[String,File]`,`Pair[File,File]` etc

**Comment by geoffjentry** [comment]
Pinging @ruchim as she & I were just talking about this.

Good news @patmagee - this might already be happening :)

**Comment by patmagee** [comment]
awesome news @geoffjentry. I wonder if in a similar vein, something like `sum( <Array[Int] | Array[Float] > )` would make sense

**Comment by ruchim** [comment]
Hey @patmagee,

There was recent discussion on what a user really wants to do and it seems like everything boiled down to a user being able to choose disk size based on the composite file size of all input Files in a task. Based on that, we'd discussed adding in a parameterless task-level function `inputSize()` in WDL that determines all the input files that will need to be localized for a task and sums up the sizes of all those files to return  Float (the same type returned by `size()`). This would mean that whether your files are wrapped in an Array, Map, or a combination of iterable types, you can extract the information you need through one single function call.

**Comment by patmagee** [comment]
Hey @ruchim this is indeed the only use case that I desire as well. A function that returns the total size of all inputs would be actually phenomenal, and I would definitely +1 that.

**Comment by dheiman** [comment]
@ruchim, one caveat to what you've mentioned is that the `runtime` directive `disk: "local-disk <size_in_gb> [HDD|SDD]"` takes an `Int`, not a `Float`, and currently there is no `ceil` function to do the necessary conversion.

**Comment by patmagee** [comment]
@dheiman `ceil` was recently added as a standard engine function. see documentation here: https://github.com/openwdl/wdl/blob/master/versions/draft-2/SPEC.md#int-floorfloat-int-ceilfloat-and-int-roundfloat

**Comment by dheiman** [comment]
@patmagee Awesome! I hadn't seen that - I withdraw my comment then!

**Comment by cjllanwarne** [comment]
I believe this was addressed in https://github.com/openwdl/wdl/pull/169 - can we close this issue?
