### ISSUE TITLE
Simple string "contains" checks

### ISSUE THREAD

**Issue by cjllanwarne** [openwdl/wdl#133]
To make life easier for authors doing string checks like in https://gatkforums.broadinstitute.org/wdl/discussion/10354/multiple-backends-for-cromwell#latest

Eg:
```
File f
Boolean a = endsWith(basename(f), ".suffix")
Boolean b = startsWith(basename(f), "prefix.")
Boolean c = contains(basename(f), ".middle.")
```

Draft implementation: https://github.com/openwdl/wdl/commits/133-string-find/

**Comment by patmagee** [comment]
I would be interested to see if there are any other use cases for this. In my experience I really have not come across any workflows that would have benefitted from having this type of logic. This type of thing is really useful when it comes to running non-deterministic workflows which try to account for all possible scenarios, But in general I am not sure that applies to most `WDL`s

**Comment by antonkulaga** [comment]
@patmagee  you ask to show usecase for very basic features are you serious or just making fun? Every second workflow I write needs contains or ends/startswith.

**Comment by patmagee** [comment]
@antonkulaga I would appreciate if you engaged in positive discussion in the issue forums, following our [Code of Conduct](https://github.com/openwdl/wdl/blob/main/CODE_OF_CONDUCT.md)

You have to remember this is a 4 year old ticket. What that means is first of all, WDL of 4 years ago was very different then it is today. Control flow in the language was minimal, or at least minimally defined and supported. Optional outputs were not even a thing either. So In that context I believe it makes sense to question the inclusion of new engine functions like these.

Secondly, being 4 years old, this tickets has yet to gain the support to transition into an RFC. If you are really excited about this change, I would recommend creating an RFC discussion over on the [discussion board](https://github.com/openwdl/wdl/discussions). You could even go so far as to support the RFC with a PR and potentially even provide a reference implementation in miniwdl

**Comment by markjschreiber** [comment]
Would the pattern be allowed to be a regex? That would certainly be cool but it does open a potential can of worms where people would then naturally want to be able to inspect the match for capture groups which goes beyond a simple boolean response.
