### ISSUE TITLE
Make toolkit more prominent in website

### ISSUE THREAD

**Issue by danbills** [openwdl/wdl#136]
We have a bunch of awesome tools for WDL!  Unfortunately I miss the roundup all the time.

It'd be nice to make the link more prominent, perhaps as one of the highlighted pieces?

I understand this is a little more noisy, was thinking perhaps listing these things vertically may help.

Anyway I crafted this professional drawing to be more specific

![image](https://user-images.githubusercontent.com/165320/30596487-3fb4ef6e-9d22-11e7-81db-2261d2b18ee1.png)

**Comment by danbills** [comment]
pinging @vdauwera for thoughts

**Comment by vdauwera** [comment]
I think you missed your calling as a graphic designer Dan.

Totally agree with you on the need to amp up the visibility of the toolkit. We added that page very recently and just haven't had time to update the homepage. Which is due for a facelift anyway.  Probably won't happen in the next couple of weeks, to be frank, but maybe after that once all of the quarterly goals hubbub settles down.
