### ISSUE TITLE
either make an explicit Directory type or explicitly treat Directories as Files in specs

### ISSUE THREAD

**Issue by antonkulaga** [openwdl/wdl#147]
As it is very common for a lot of tools to take folder as an input (RNA STAR is a good example) it will be beneficial to clarify in the specs if File is also a Folder (like in Linux) or (if not) introduce a Folder type.

Based on this Cromwell issue https://github.com/broadinstitute/cromwell/issues/2735

**Comment by patmagee** [comment]
This was implemented here: https://github.com/openwdl/wdl/pull/241
