### ISSUE TITLE
newbie questions

### ISSUE THREAD

**Issue by matthdsm** [openwdl/wdl#150]
Hi 

I'm just getting started with WDL and I have some questions:
- What is the preferred input type for directories? Are they `String` or `File` types?
- is it possible to "import" tasks from another workflow, or some general 'tasks' file, so the same task can be used in multiple workflows?
- Does WDL support unix pipes? I know it's possible to use the pipe "`|`" inside a task, but is there any support for pipes between tasks.
- What is the preferred approach for commands that are normally piped?
is it better to do
```
command{
  cmd1 | cmd2 | cmd3
}
```
or to separate all commands into different tasks and let them write to stdout, using that as input for the next task?

Thanks a lot.
M

PS: If there's another place better suited for such question, please let me know so I can move it.

**Comment by matthdsm** [comment]
Also, when using the docker runtime, how can we specify volumes to be mounted? This is the case for pretty much every tool that requires some kind of reference data.

For example,  when using a `biocontainers` image for `bowtie2` you'd need to mount a directory with reference data for the mapping, next to a directory with the input data.

**Comment by cjllanwarne** [comment]
hey @matthdsm I suggest you post this over in the [WDL forum](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team) since:
- It won't resolved via a PR in the repo
- You might also find some answers to future questions
- Your answers might (I'm sure they will!) be useful to others in the future!

**Comment by matthdsm** [comment]
Allright, thanks!
