### ISSUE TITLE
Error when using `prefix()` with an optional array.

### ISSUE THREAD

**Issue by genomics-geek** [openwdl/wdl#152]
Is it possible to use `prefix()` with an optional input?

I was trying to do something like this:

```wdl
task DoSomething {
	Array[File] ? intervals = []

	command {
		${sep=" " prefix("--intervals ", intervals)}
	}
}
```

However I get this error:
`java.lang.UnsupportedOperationException: Could not evaluate expression: prefix("--intervals", intervals)`

But it works as expected when I use it this way:

```wdl
task DoSomething {
	Array[File] intervals

	command {
		${sep=" " prefix("--intervals ", intervals)}
	}
}
```

Is this expected? Or am I doing something wrong?

**Comment by geoffjentry** [comment]
Hi - your best bet for questions like this would be to ask in the [support forum](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team). It's still branded (and primarily staffed) by the original Broad team, but that's still where we're trying to funnel user questions.

**Comment by genomics-geek** [comment]
@geoffjentry - sounds good. I will post it on the forum.
