### ISSUE TITLE
The need for an "Unlocalized File" type

### ISSUE THREAD

**Issue by yfarjoun** [openwdl/wdl#158]
wdl writers currently have two options when dealing with files:

1. Use a File type and have the file "localized" and sanitized (WRT to the original name of the file).
2. Use a String type, and access the raw URL directly (if you can), and deal with resulting issues (see below).

<separator between lists>

1. Is good for small files and "dumb" programs. It also makes call-caching possible as the MD5 of the file can be stored in a DB
2. Is a good idea when accessing many small parts of large files (say combining 80K vcfs). It requires smarter programs (that know how to interact with an index and to talk to the requisite filesystem, be it s3:// gs:// or http://. The problem with this option is that call-caching is effectively disabled here, as the variable will have a different raw url with every invocation of the task.

Since more and more of our pipelines are trying to use String instead of File as a cost-saving measure, I think it makes sense to see how we could enable call-caching without localizing a file. I have some ideas:

1. Have some decoration on a File type indicate that it should be not localized and that the raw string should be used instead. This should enable call-caching without localization, as the implementations should be able to md5 the underlying file)
2. In the run-time attributes (or elsewhere), indicate which variables shouldn't be localized (ugly)
3. Add a new type, say `RemoteFile` which acts like the solution in 1 but without a decoration.
4. Allow a decoration (mutable?) to indicate that changes in this variable should not invalidate a cache, then one could pull in only the MD5 of the file (which would be cached) as an additional variable from a separate task and and the String pointer to the file as `mutable`, thus guarantee that if the file changes, the task is run and the cache is pointing to the right place (possibly easiest to implement, but hardest to maintain as a wdl author)

Other ideas or thoughts on the matter?

**Comment by abaumann** [comment]
+1 - also needed for output files where a tool might write/stream directly to another location (rather than a file local to the VM being delocalized and added to call caching)

**Comment by geoffjentry** [comment]
I'll add that I've seen this request countless times, there's clearly a need for it. People suggesting it always have a different name for the concept (and often declare that previous names are awful and wrong, go figure), but the idea always remains the same -> essentially something which is treated as a `File` within WDL but a `String` for command purposes 

If someone wants to make a concrete proposal I'd be all for it existing.

**Comment by patmagee** [comment]
Before we get to the proposal, I would Just suggest that we use option `3` over any type of Syntactic decoration. We do not use decorators in WDL as of yet, and introducing them would not only add complexity for the user at this time, but would probably add quite significant complexity to implementors.

**Comment by yfarjoun** [comment]
Thanks @patmagee, this was the reason I opened an issue before writing a PR....

just to clarify though, you say "We do not use decorators in WDL as of yet" however, I would consider that the "?" is a decoration that means "Optional". 

While I agree that decorations can make things more confusing and complicated, the advantage is having fewer actual types. 

In this case, since the modification would only be of a single type (unlike ?) option 3 is my personal favorite as well, and was planning to write the PR in that spirit.

**Comment by geoffjentry** [comment]
I've been picturing this as a new type, FWIW.

re decorations, I know that the DNAnexus folks (pinging @mlin @orodeh) have talked about adding a "hint" to the file type that something is streamable, such that an implementation can choose to do something smart with that information or not. IIRC their proposal was going to be a decorator along the lines of Yossi's `?` example.

**Comment by yfarjoun** [comment]
So I started looking at writing a PR for this and I realized that declaring "RemoteFile" to be it's own new type comes with a host of complications that we might want to avoid:
- we will need to define all the legal operators between String, File and RemoteFile (currently we have only String and File)
- we might feel the need to define read_remote_file() just to get the right return value, or need to explain that you can just do read_file() and then "cast" to RemoteFile
- we would need to think long and hard about the implication of starting with an Array[File] and then "casting" it to an Array[RemoteFile] etc.

The reason that this is not what we want is that the difference between a File and a RemoteFile is only "felt" in one places: Upon input to a task
 
This makes the case stronger that it should be a modifier and not it's own type....so that we could write something like this:
```wdl

Workflow tryThis{

   File bucket  = "gs://bigFiles"
   File directory = bucket + "/do/not/download/use/"
   String filename = "biggie.bam"

   call getHeader{input: file=directory, fileName=filename}
}

task getHeader{
   File* input // * indicates that file is remote, access as a string, but be aware of md5 for call-caching
   command {
   // let's pretend that samtools can open gs:// links
   samtools view -h ${input} header.out
   }
   output {
      File header = "header.out"
   }
}

**Comment by yfarjoun** [comment]
@LeeTL1220 you might want to chime in here.

**Comment by orodeh** [comment]
@mlin and myself did suggest adding a "stream" annotation inside the `parameter_meta` section. This is implemented and described in the [dxWDL README](https://github.com/dnanexus/dxWDL#extensions-experimental). I don't have a preference between an annotation and a modifier.

While porting the GATK4 pipeline, I realized it was using remote-files, as @yfarjoun describes. The implementation calls [Google NIO](https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/blob/master/PairedEndSingleSampleWf.md#use-of-google-nio) from the GATK4 jar file. It would be much nicer to have a proper declaration of these files, currently, their type is `String`.

**Comment by patmagee** [comment]
this is implemented in various different ways in the engines (ie cromwell `localization_optional`).
