### ISSUE TITLE
Encoding in string interpolation and file I/O

### ISSUE THREAD

**Issue by rasmuse** [openwdl/wdl#165]
Hi WDL team,

First, please let me know if I should have posted this in the forum instead. If so, I can close this issue and open a forum thread.

## The issue

The WDL spec does not say anything about the encoding used by file I/O operations (e.g. `read_string()`, `write_lines()`, and a bunch more).

The WDL spec also does not say anything about the encoding used in string interpolation (e.g., if I interpolate a `String` into a `command` section.

If there is an obvious and established practice it would be good to make it formal. Otherwise I guess a discussion is needed first.

I would be all for "`utf-8` everywhere" as a rule for now. I don't know if anyone can come up with use cases where handling other encodings would be needed or at least useful.

## Context

This is my first active involvment after looking at this language for a while. The core ideas align very well with ideas I've had for several years on scientific workflow systems. It's awesome that the language is human-writeable and readable and furthermore that outputs can "live" as variables in the workflow, e.g., for interpolation, transforming and serializing outputs, etc. So now I'm toying with the idea of building my own tools that primarily accept WDL.

**Comment by patmagee** [comment]
WDL is defined as UTF everywhere within the global grammar rules of the specification
