### ISSUE TITLE
Array addition and subtraction

### ISSUE THREAD

**Issue by cjllanwarne** [openwdl/wdl#170]
A way to add elements to (and remove elements from) an array would be really helpful. Eg something like

```wdl
Array foo = range(5) # ie [ 0, 1, 2, 3, 4 ]
Array foo2 = foo + 6 # ie [ 0, 1, 2, 3, 4, 6 ]
Array foo3 = foo2 + range(2) # ie [ 0, 1, 2, 3, 4, 6, 0, 1 ]
Array foo4 = foo3 - 1 # Question: do we remove the first, the last, or both 1's?
Array foo5 = foo4 - [4, 6] # Remove both the 4 and the 6
```

**Comment by cjllanwarne** [comment]
Questions:
- Should we use `++` vs `+` for single-element vs entire array appending?
- What should we subtract if we have multiple matching elements?

**Comment by LeeTL1220** [comment]
@cjllanwarne I think python does remove by removing the first value in the list.  Note that python does not have a list subtraction operator.  You really have to call `list.remove(...)`, which removes the first match in the list.

**Comment by yfarjoun** [comment]
@cjllanwarne I would treat `a-b` as "iterate over b removing the first occurrence of each element from a".

**Comment by geoffjentry** [comment]
At sorta/kinda first blush (s/k in that I feel like similar topics have been raised in the past) I am not particularly keen on adding this sort of power to the language. This seems like a prime example of my concern of WDL becoming increasingly like a proper programming language

**Comment by yfarjoun** [comment]
Do you have a better solution for manipulating arrays? Should one have to spin up a VM for that (what we do now...)

**Comment by orodeh** [comment]
@yfarjoun This is, indeed, an issue. I agree with @geoffjentry that we don't want to slip into making WDL a general purpose programming language; how to avoid that isn't clear. 

One option, that I implement in dxWDL, is to distinguish between *light weight* and *heavy weight* tasks. Light tasks have an empty shell command section, and I do not localize files for them. They are really more like methods than tasks. Perhaps someone has a creative idea for how to improve upon this idea.

**Comment by cjllanwarne** [comment]
IMO there's a long way to go before "adding a 3 to the end of my array" becomes "general purpose programming language". 

Think of it like this: the programming knowledge you'd need to get that to work in a command is far and above what you have to know to understand that `[1, 2] + 3` == `[1, 2, 3]`.

That said, I think we **should** be suspicious of anything that's not absolutely obvious (eg the subtraction where opinions clearly differ on what it should look like)

**Comment by yfarjoun** [comment]
Try that on Matlab or r... See what you get.

**Comment by patmagee** [comment]
I think these are important features. I have come across situations where concatenating two result sets was annoyingly difficult. IE spinning up a new VM for a simple echo of two separate lists.  So I definitely support this.

What I would disagree with the current suggestion is how the concatenation is performed. I think the types should match, which would then make this equivalent to a python `extend` operation as opposed to an append.  In this case, even single elements should be wrapped as an array. To me this looks more consistent

```wdl
Array[Int] x = [1,2]
Array[Int] y = [1,2] + [3]
```

Additionally, I do not think that we necessarily need the corresponding binary operator `-`. most languages do not support list subtraction as a form of removal.  the other reasonable option would be to have an engine function which performs this ie:

```wdl
Array[Int] x = [1,2]
Array[Int] y = [1,2] + [3]
Array[Int] z = remove(y,1)
```

**Comment by cjllanwarne** [comment]
I like @patmagee 's suggestion most here. It's too late for this to become a 1.0 feature but we could (should) definitely add this to our list for 1.1.

**Comment by fpichon** [comment]
I found some work around for people that need it : 
Array[Int] x = [1,2]
Array[Int] y = [3]
Array[Int] z = flatten( [ x , y ] )
Hope it helps.

**Comment by yfarjoun** [comment]
This is great...but I couldn't find `flatten` in the documentation....it does work...so this seems to be a documentation issue.

**Comment by FabienVadim** [comment]
You can found some information there : https://github.com/openwdl/wdl/blob/master/versions/draft-3/SPEC.md#arrayx-flattenarrayarrayx

**Comment by yfarjoun** [comment]
huh...I'm not sure why I didn't see it before...sorry.

**Comment by patmagee** [comment]
I think `flatten` accomplishes this for now, unles someone wants to take up the rains on this

**Comment by freeseek** [comment]
While `flatten()` does accomplish the job of adding elements to an array, it would be nice to have something that also removes elements. Maybe something like `head(Int, Array[X])` and `tail(Int, Array[X])` with the integer allowed to be also negative so that you can mimic bash scenarios such as `tail -n2 file.txt` and `tail -n+2 file.txt`

**Comment by kjaisingh** [comment]
+1 - deletion would be very useful, especially given that array comprehensions are not possible. It is quite cumbersome to remove a single element from an Array.
