### ISSUE TITLE
Need a way to use Directories as input arguments to tasks/workflows

### ISSUE THREAD

**Issue by jonn-smith** [openwdl/wdl#176]
There is currently no good way to specify a directory as an input argument to a task/workflow.  You must specify it as a string and do checks in the command block.

I suggest updating the `file` input keyword to work on directories as well.

**Comment by cjllanwarne** [comment]
Please have a look at and comment on the proposal to address this in #173 !

**Comment by patmagee** [comment]
#173 is already addressing this
