### ISSUE TITLE
Should glob() have a specified output order?

### ISSUE THREAD

**Issue by mlin** [openwdl/wdl#181]
The order of the array returned by glob() is unspecified, so if my task has

```
output {
  Array[File] results = glob("*.vcf.gz")
}
```

I don't seem to have a straightforward way to control the order of the output array, even if e.g. I carefully name my output files so that they order in a certain way lexicographically.

**Comment by cjllanwarne** [comment]
I can maybe include something to clarify this in my globs PR. 

The glob results should be the set of items, and in the same order, as an invocation of bash would produce on the VM.

**Comment by cjllanwarne** [comment]
I just updated #180 to cover output order
