### ISSUE TITLE
<<CODE  CODE blocks not documented

### ISSUE THREAD

**Issue by rhpvorderman** [openwdl/wdl#191]
From the examples I see that I can use this neat functionality.
```WDL
task hello {
    String name
    command {
        python <<CODE
        print "Hello ${name}!"
        CODE
    }
    output {
        String greeting = read_string(stdout())
    }
}
```
But I can not find it anywhere in the documentation. What does <<CODE CODE actually do? Can I choose any random interpreter such as 
```
bash <<CODE
echo "Hello ${name}!" 
CODE
```
What languages are supported? Can other block markers be used? How to define the interpreter (python3 vs python2 for example) etc.
EDIT: and also the tutorials did not contain this information.

Maybe I am looking in the wrong places, but even an extended web search across the cromwell documentation, the wdl spec, the wdl issue tracker, the cromwell issue tracker and the forums did not reveal any information about this feature.

**Comment by mcovarr** [comment]
This actually isn't a WDL feature at all, it's shell "[here-doc](http://tldp.org/LDP/abs/html/here-docs.html)" syntax.

**Comment by rhpvorderman** [comment]
That explains a lot. Thanks!
Now I am a little embarrassed by my ignorance. But I still wonder if it would be useful to put a link to the here-doc syntax somewhere in the documentation. The WDL tutorials for example? It is a very useful feature and it enhances WDL tasks to a great extent. It would do a great job to enlighten the ignorant (such as myself).

**Comment by patmagee** [comment]
I wouldnt place this necessarily in any of the language documention, but if we ever get around to do `Getting Started` or `Tutorials` or `Examples` sections for creating and writing WDL, then this would be a great place to put it, as a complex example.
