### ISSUE TITLE
clarification for File? and read_tsv(emptyFile)

### ISSUE THREAD

**Issue by antonkulaga** [openwdl/wdl#196]
I think that it should be clarified in the specification that:
1) File? myfile = "does_not_exist" should return null instead of crashing workflow
2) read_tsv(emptyFile) should return Array[Array[String]] as it is what most libs and tools generate when they are provided an empty array/dictionary for tsv generation.

If this is not clarified in some implementations those functions may work fine, while in others lead to workflow_errors.

**Comment by cjllanwarne** [comment]
I assume your item (1) is referring to outputs from a task (rather than in the middle of a workflow)?

**Comment by jdidion** [comment]
The section on [Files and Optional Outputs](https://github.com/openwdl/wdl/blob/wdl-1.2/SPEC.md#files-and-optional-outputs) addresses #1.

I agree that all of the `read_*` should have the clarification added that reading from an existing but empty file returns an empty value rather than `None`.
