### ISSUE TITLE
Clarify short-circuiting of &&, || and if/then/else expressions

### ISSUE THREAD

**Issue by cjllanwarne** [openwdl/wdl#199]
I think most people would expect this (https://github.com/broadinstitute/cromwell/issues/3384) to work, but it's probably worth making that explicit in the SPEC.

Draft implementation: https://github.com/openwdl/wdl/tree/199-short-circuit

**Comment by patmagee** [comment]
This does not work? I agree though, this should probably work out of the box and be an expected behaviour of all implemenations.

**Comment by cjllanwarne** [comment]
@patmagee this was an oversight in Cromwell's implementation. I guess the fact that it lasted this long means it's a bit of an edge case but it's still worth sorting out.

This works as you'd expect now in Cromwell 31 (released a few days ago) and this is the corresponding "clarify the spec"

**Comment by patmagee** [comment]
@cjllanwarne is this really a spec issue or an issue for the implementor? it seems natural to assume short-circuiting without having to define it explicitly anywhere. If you agree we can go ahead and close this

**Comment by cjllanwarne** [comment]
I think the example in the description is a valid use case and an example of why we can't just leave it to the implementation (because if an implementation doesn't short-circuit, that workflow is a failure and if it does short circuit then it's a success).

Therefore, IMO it's more than just an optimization detail and deserves a one line addition to the spec guarantee the same behavior across implementations.
