### ISSUE TITLE
output_meta section for tasks and workflows

### ISSUE THREAD

**Issue by wdesouza** [openwdl/wdl#204]
The `parameter_meta` section is very useful for describing tools with many parameters. It would be nice to have a `output_meta` to describe task and workflows outputs.

``` wdl
task example {
  String name

  command {
    echo "Hello, ${name}!"
  }

  output {
    File message = stdout()
  }

  parameter_meta {
    name: "Your name."
  }

  output_meta {
    message: "A file containing a message."
  }
}

workflow test {
  call example {
    input:
      name = "John"
  }
}
```

**Comment by patmagee** [comment]
@cjllanwarne @geoffjentry not sure if this is allowed currently, but wouldnt it make sense just to re-use the output meta section? The outputs occupy the same namespace as the inputs, and therefore there would be no collisions in their names.

**Comment by ruchim** [comment]
@patmagee I like your proposal of making it so that both inputs and outputs are can be documented inside the parameter_meta block. Sounds like it will require updating the spec, which currently requires keys of the `parameter_meta` block to be inside the command, which isn't always true/possible for outputs:

https://github.com/openwdl/wdl/blob/master/versions/draft-3/SPEC.md#parameter-metadata-section
```Additional requirement: Any key in this section MUST correspond to a parameter in the command line```

**Comment by patmagee** [comment]
@ruchim, To be honest, I never even knew the `parameter_meta`  was restricted to parameters used within the command line. Its probably worth clarifying at some point in the spec.

**Comment by ambrosejcarr** [comment]
@ruchim Is `meta` restricted to workflows only? I'd love for that to be enabled for tasks, if so.

**Comment by patmagee** [comment]
@ruchim @cjllanwarne correct me if I am wrong but as far as I can tell there is nothing specifically forbidding the use of `parameter_meta` for outputs at the grammar level. Any restrictions are at the level of the implementation and i think are fairly loosely enforced even now as it is

@ambrosejcarr `meta` is both task and `wf` level

**Comment by jdidion** [comment]
@patmagee yes, `parameter_meta` can contain input and output parameters. I think we can close this issue.
