### ISSUE TITLE
enable link for Spec i.e. "Draft language specification"

### ISSUE THREAD

**Issue by danbills** [openwdl/wdl#210]
Currently on openwdl.org there is a set of links, one of which says "draft language specification."  Unfortunately it is not a hyperlink!

Generally speaking as a user I would like quick access to the spec from the openwdl homepage.

**Comment by cjllanwarne** [comment]
➕ 

It could probably also be updated to say "version 1.0 of the language specification" now

**Comment by geoffjentry** [comment]
HTML fail. There *was* a hyperlink there, it just wasn't anchored to anything :)

**Comment by rexwangcc** [comment]
The links in https://software.broadinstitute.org/wdl/documentation/spec#fully-qualified-names--namespaced-identifiers still don't work, do we have plans to fix the anchors? :octocat:

**Comment by geoffjentry** [comment]
@vdauwera see the comment from @rexwangcc
