### ISSUE TITLE
Parameter meta for structs

### ISSUE THREAD

**Issue by cjllanwarne** [openwdl/wdl#215]
Seems like an obvious extension to having `structs` and `parameter_meta` sections, eg:
```wdl
struct foo {
  File f
  Int i

  parameter_meta {
    f: "A file containing a set of important information"
    i: "A precomputed value regarding the file"
  }
}
```

Draft implementation: https://github.com/openwdl/wdl/tree/215-struct-parameter-meta

**Comment by patmagee** [comment]
Makes sense to me! especially since overhead and difficulty of implementation is probably 0 for this. Could you wrap this in a PR?

**Comment by cjllanwarne** [comment]
@patmagee @geoffjentry are we accepting future version PRs yet? 

Side question: is there a work-in-progress name for the next version to avoid proliferating not-quite-`version 1.1` WDLs (like we did with `draft-3` and `1.0`)?

**Comment by geoffjentry** [comment]
@cjllanwarne Yes-  the infrastructure is in place, the wdl 1.0 announcement just hasn't happened

**Comment by patmagee** [comment]
@cjllanwarne 
can you please convert this to a PR if you get a chance?
