### ISSUE TITLE
Debug Messages

### ISSUE THREAD

**Issue by cjllanwarne** [openwdl/wdl#224]
I'm moving PR #223 into issue form to get more discussion on "what" (if anything) to do, since it retrospect it's far too easy for the "what" to get lost amongst comments on the specific suggestion when submitted in PR form.

What I really wanted to make is a way to write debug logs so that as a workflow is progressing - or even if it fails, I can see a log of what's happened inside the workflow. Ideally:

* They'd be obvious to a reader (ie not some opaque "trick" that achieves the goal)
* They'd be turn-offable (ie if an engine decides not to log debug messages, it doesn't even need to evaluate the expressions)
* The language would not make any demand on the engine for this - ie leave it up to the engine whether (and if so, how) to get these messages out to the user.

From there it seemed natural to also allow `info`-level logs but they weren't really my goal in #223.

Questions:

* If you're a WDL author:
  * would something like this be useful?
  * do you have an example of when something like this would have helped - and if so what did you wish you could just do?
* If you're an engine developer:
  * Does this whole idea fill you with fear?
* Everyone
  * Is this *too much DSL*?
  * Is a workflow description the right place to put self-help debug messages? If not, where might be better?
  * Are we better off relying on relying on engines to act as debuggers? (ie do nothing in the language, wait for engines to allow setting breakpoints and stepping through the workflow?)
  * Is doing nothing (and allowing workarounds to proliferate) worse in the long run than doing something small and not-quite-perfect?

**Comment by patmagee** [comment]
@cjllanwarne personally I would prefer to leave this to the engine to decide. the WDL language is realistically dumb, and in that sense, it should not know about things like debugging and messages. Those are by there very nature implementation details. 

to answer some of your questions:

- Yes something like this would have been useful in some scenarios. However What I find most useful in general is a combination of properly writing my own tasks to do logging to stderr, and using the engines' logs.
- I do not think the workflow description would be the right place, at least no the WDL specification. If an implementor wants to overlay some fancy visuals on top of well then that's a separate issue
- Yes, yes it is too much DSL haha and should just let the debuggers work within the engines. 
- I am not sure how this really would solve workarounds from proliferating. What we truly need is a good ol style guide to point everyone too when in doubt. Similar to PEP 8. short of that we will not solve workarounds.

Some questions of my own
- how would a user retrieve log messages? 
- What would the log messages look like??
- How are these log messages different than engine specific debug logs?
