### ISSUE TITLE
Allow length to work on optional arrays

### ISSUE THREAD

**Issue by cjllanwarne** [openwdl/wdl#234]
Right now:
```wdl
  input {
    Array[Int] xs = [1, 2, 3]
    Array[Int]? ys = [1, 2, 3]
    Array[Int]? zs # Imagine this doesn't get supplied
  }

  Int len_xs = length(xs) # Returns 3
  Int len_ys = length(ys) # Doesn't work
  Int len_zs = length(zs) # Doesn't work
```

It seems sensible to me to also allow behavior like:
```wdl
  input {
    Array[Int] xs = [1, 2, 3]
    Array[Int]? ys = [1, 2, 3]
    Array[Int]? zs # Imagine this doesn't get supplied
  }

  Int len_xs = length(xs) # Returns 3
  Int len_ys = length(ys) # Returns 3
  Int len_zs = length(zs) # Returns 0
```

**Comment by EvanTheB** [comment]
existential difference between optional and empty array aside, this is sensible. :+1:

**Comment by yfarjoun** [comment]
I think that `length` on optional array should return an optional int. This gives much more consistent behavior and doesn't hide a non-existent array as an empty array (not the same!!)

**Comment by rhpvorderman** [comment]
I agree partly @yfarjoun. But this is still not a good solution. `length` should always return an int. Not sometimes an optional int. This will mess with consistency.

@cjllanwarne. What is the advantage of this PR compared to length(select_all(zs))`? This gives the same effect, without casting undefined optional arrays into empty arrays, which should never happen.
The WDL spec already has the toolset to handle this problem in my opinion.

**Comment by LeeTL1220** [comment]
I agree with @yfarjoun  ...  There needs to be a difference when an input is null versus empty.  These are not the same.  As much as propagation of `null` disturbs me...

And if I want `length(null)` to just return a zero, I can just use `select_first([...,[]])`.

**Comment by EvanTheB** [comment]
@LeeTL1220  `select_first` is defined to work on Arrays of Optional, not Optional Arrays. And if there is not anything in the array, the engine should crash. 

@rhpvorderman The same applies for your example, this PR is for optional arrays not arrays of optional.

**Comment by yfarjoun** [comment]
right....so 

`select_first([ maybeArray, []])`

will either return maybeArray (if present) or [] (if not) after which you can run length and get 0 when array is not present.

**Comment by rhpvorderman** [comment]
Thanks @EvanTheB for pointing this out. 
Still as @LeeTL1220 points out and @yfarjoun gives a nice example `select_first([ maybeArray, [] ]) solves this problem. It looks ugly for sure, but at least it is explicit. When optionals go to non-optionals I prefer an explicit conversion in all cases. Having an implicit conversion as proposed here will lead to confusion and debugging of errors will be much harder.

**Comment by patmagee** [comment]
I like @yfarjoun solution. Similar to what @LeeTL1220 said, a missing optional array is distinct from an empty array .  To me its quite consistent to expect an optional array to lead to an optional integer

**Comment by patmagee** [comment]
closing this as it seems the agreed upon solution in the current spec is:
```
select_first([ maybeArray, []])
```
