### ISSUE TITLE
Dealing with Large Int Values

### ISSUE THREAD

**Issue by jsotobroad** [openwdl/wdl#242]
I ran a workflow that failed because the `Int` value was greater than `MAX_INT` presumably.  This is the error I'm getting when I run into this.
```
message: Workflow failed
causedBy: 
message: Failed to evaluate job outputs
causedBy: 
message: Bad output 't.total_reads': For input string: "4133332354"
message: Bad output 't.mapped_reads': For input string: "4073908008"
```
my task outputs are
```
output{
Int total_reads = read_int("total_reads.txt")
Int mapped_reads = read_int("mapped_reads.txt")
Int unmapped_reads = read_int("unmapped_reads.txt")
}
```
I can deal with this by treating everything as a string but there should probably be a way to specify like `read_long()` or just default `Int` to be `BigInt` or something along those lines.

**Comment by EvanTheB** [comment]
I have a PR trying to define what the types in WDL should guarantee: https://github.com/openwdl/wdl/pull/235

**Comment by patmagee** [comment]
@jsotobroad it lloks like the changes from #235 should address this. Please see  https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#numeric-behavior for more information. Please note, this behaviour will be a future release of `WDL`
