### ISSUE TITLE
Version 1.0 spec incorrect on struct from object literal

### ISSUE THREAD

**Issue by kshakir** [openwdl/wdl#246]
https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#struct-assignment-from-object-literal

The above example lists:

```wdl
Person a = {"name": "John","age": 30}
```

Once #201 is done the above _might_ work, but this definitely isn't valid in 1.0.

The example should read something like:

```wdl
Person a = object {name: "John", age: 30}
```

There may be other locations with similar struct-docs issues.

**Comment by patmagee** [comment]
Fixed in #297
