### ISSUE TITLE
Small floats render in exponential notation

### ISSUE THREAD

**Issue by helgridly** [openwdl/wdl#249]
I have a WDL with command block `samtools view -s ${frac} -b ${bampath} -o ${outname}.bam`, where `frac` is a `Float` type.

Downstream, in the PAPI script, this had turned into `samtools view -s 5.0E-5 -b ...<etc>`, which rather confused samtools.

Someone somewhere decided to render `0.00005` as `5.0E-5`, and it wasn't me. Can you help?

(Adam N said to reference WDL draft-2, so I am hereby doing that.)

**Comment by helgridly** [comment]
Moved to https://github.com/broadinstitute/cromwell/issues/4049 by request.

**Comment by EvanTheB** [comment]
I made an attempt to define what floats were and how they should be formatted: https://github.com/openwdl/wdl/pull/235
