### ISSUE TITLE
new keyword "error" for stoping a workflow with an error message

### ISSUE THREAD

**Issue by yfarjoun** [openwdl/wdl#254]
We have been running into situations where the input data doesn't fit the assumptions of the workflow. while might cause a downstream error to happen on its own, the error message accompanying this event usually doesn't point at the correct source of the problem.  

This could be resolved by some if statements in the wdl, running some sanity checks on the input, but then there is no way to gracefully and informatively fail. An `error` keyword would allow authors to fail a workflow without having to spin up a vm that fails (i.e. returns error code 1) in order to inform the user of the true reason for failure.

**Comment by geoffjentry** [comment]
This seems like it is/should be implementation specific?

**Comment by yfarjoun** [comment]
why? a workflow language should have an easy, fail-proof way to communicate
that there's an error...

**Comment by geoffjentry** [comment]
I somewhat misunderstood what you were asking for - was keying on "having to spin up a vm" which is absolutely implementation specific.

**Comment by rhpvorderman** [comment]
An error with a boolean and a stringwould be a nice way to implement this:
```
error True "Error is true here. So it errors"
# Or
error False "This message never shows"
```

This would be useful in a case where a tool requires different inputs. (Files on the command line or a list of files in a text file for example). 

Something like this
```
error !(defined(commandlineFiles) || defined(fileList)) "Need to define either commandlineFiles or fileList"
error (defined(commandlineFiles) && defined(fileList)) "fileList can not be used in combination with commandlineFiles"
```

**Comment by yfarjoun** [comment]
currently we use this:

```wdl 
#Print given message to stderr and return an error
task ErrorWithMessage{
    input {
        String message
    }
    command <<<
    >&2 echo "Error: ~{message}"
    exit 1
    >>>
     runtime {
        docker: "ubuntu"
    }
}
```

**Comment by rhpvorderman** [comment]
@yfarjoun , as your example clearly shows this is quite verbose and impractical, just for the printing of an error message.
Can you make a pull request so we can have a discussion how to implement this in the spec?

**Comment by cjllanwarne** [comment]
@rhpvorderman I think the "boolean" part could be handled by the existing `if { }` and `if / then / else` constructs. I agree that supplying a message along with the error would be nice.

Eg in workflows?
```wdl
workflow foo {
  call task_a
  if (!task_a.good_result) {
    error("task_a's result was not good")
  }
}
```

And in tasks?
```wdl
task foo {
  input {
    Int x
  }
  Int y = if x > 5 then x else error("Input x was not good")
  ...
}
```

**Comment by rhpvorderman** [comment]
@cjllanwarne . That is much better than my suggestion. Looks great!

**Comment by rhpvorderman** [comment]
I agree with @pshapiro4broad that the syntactic sugar makes things unnecessary complex. Using the already existing if clauses will be better.

**Comment by DavyCats** [comment]
If I'm not mistaken, the normal if clause can't be used in tasks, so you won't be able to use the `error` function in tasks in that case. I'm not sure whether that would be an issue or not, you'll probably want to do most of these checks in workflows anyway.

**Comment by pshapiro4broad** [comment]
@DavyCats you're right; I missed that this was part of a task. Sorry for the confusion, I wish there was a way to retract my comment but keep it on the record.

I'm still unsure of the value in adding `error()` for tasks, but if we did, an expression form as @cjllanwarne describes would work.

**Comment by patmagee** [comment]
closing this as it seems like the discussion is leaning towards not implementing an error feature
