### ISSUE TITLE
Allow passthrough of inputs from the `inputs.json` to a subworkflow

### ISSUE THREAD

**Issue by TMiguelT** [openwdl/wdl#262]
Currently, all inputs to a subworkflow and any tasks inside it must be specified in the workflow that calls it. However, this results in a lot of duplication of input metadata. Each input must be listed in:
* The subworkflow task
* The subworkflow 
* The parent workflow
* The `input.json` file

A much cleaner syntax would allow the `inputs.json` to directly specify inputs into the subworkflow and its tasks. Ideally, this WDL should run: https://github.com/TMiguelT/WdlSubworkflowPassthrough

**Comment by patmagee** [comment]
There is nothing prohibiting this in the specification as far as I can tell. I would think this is an implementation detail.  @cjllanwarne @geoffjentry what do you think? If this is more an implementors issue then we can go ahead and close this

**Comment by illusional** [comment]
Hey @geoffjentry / @cjllanwarne, just wondering if Cromwell currently does this. I can't get it to work, and the spec definitely implies that you can reference a workflow's task's input ([development/SPEC.md#specifying-workflow-inputs-in-json](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#specifying-workflow-inputs-in-json)).

I am relying on it for Runtime attribute overrides (#301). If this is matter of the spec SHOULD weigh in, I'm happy to put a PR together. It's the only way you could have a 'runtime.json' specifying all the runtimes attributes required for a platform.

Some additional thoughts anyway, you should specify the call alias if one exists (so you could distinguish different calls of the same tool), and then it falls back to the task / subworkflow name.

eg: 
- `myworkflow.task1name.inputOfTask1Name`
- `myworkflow.mysubworkflowalias.taskname.inputName`

**Comment by geoffjentry** [comment]
@illusional to be clear, are you putting the task name or the call name (assuming they're not the same). That should work.

**Comment by illusional** [comment]
I put the call name, eg: call B.Bwamem as TheCallAliasForBwaMem

Then I’d put:
`myworkflow.TheCallAliasForBwaMem.myinput’ which would give me an error.

**Comment by geoffjentry** [comment]
@illusional eagle eye @cjllanwarne pointed out to me that you're using subworkflows and that's not supported. I don't see the spec being opinionated in one direction or the other, and that should be clarified. 

This is related to #217 

IMO this **should** be supported

**Comment by illusional** [comment]
Was going back through the WDL issue / PR history and found #192 as well.

**Comment by jdidion** [comment]
This is covered in the "unsatisfied task inputs" section of the v1.1 spec.
