### ISSUE TITLE
Allow read_json to also read yamls

### ISSUE THREAD

**Issue by rhpvorderman** [openwdl/wdl#264]
So the inputs can be json or yaml. So the execution engine should have yaml support anyway.

Yaml is much nicer to produce for humans. So it would be nice if `read_json` could also read yaml.
Creating a new `read_yaml` statement seems excessive to me. 

Curious to what everyones thoughts are on this subject.

**Comment by patmagee** [comment]
I think this is a good idea, although I think its really up to the independent implementation as to whether they would support reading in `yaml` AND `json`. I would not go as far as making this a hard requirement for implementors

**Comment by geoffjentry** [comment]
@patmagee I'd like to dig into this a little bit as it touches on a thread I've been having with increasing frequency in my travels. 

At the moment the WDL specification defines the format for inputs, and that format is in json. You just alluded to allowing an implementation to define their own input format as a superset. 

Recently I've been fielding various questions from folks asking for enhancements to Cromwell's input format, my pushback has always been that the input format is codified by the WDL spec and that has universally resulted in the other person stating that input format shouldn't be part of the spec whatsoever.

My larger question is:

- Should the WDL spec define input format
- If so, should alternate formats be allowed

My own $0.02 is that answering yes to both is weird as what will wind up happening is you'll start seeing non-spec compliant input files floating around, e.g. some of the complaints I've fielded about the current format come from developers of widely shared workflows who will want to only generate a single inputs file.

**Comment by patmagee** [comment]
Ive always viewed inputs files to be out of the scope of the wdl specification. For example, what if we would like to start accepting `DRS` objects in Cromwell for `File`. To me, the `JSON` definition defined within WDL fundamentally relates to the relationship between the language and the implementation, and how types are represented internally.  

IE the implementation can accept alternate input types if it so chooses, however at a language level we define how the inputs are internally represented. Internally inputs may be `JSON` like, but they are distinctly NOT json, they are `WDL`, and we define the rules around how element access works, etc. 

Going with a model like this certainly would end up being much more flexible in the long term.

I can understand the frustration from some power users not wanting to generate a different input file for a different implementation. SO to that end, I would say we recommend it as a guideline, that the `inputs` reflect the internal structure of objects in `WDL`, however, we do not have any enforcement of it. If Implementors have a different approach for defining inputs they could provide a way of generating the `inputs` file required for their pipeline.

**Comment by geoffjentry** [comment]
Either way this is somewhat academic as the WDL spec **is** currently opinionated about inputs, so someone is going to have to feel strongly enough prior to the status quo changing :) Granted I can't control what other implementations do, although IMO it'd be a bad look for Cromwell to be actively encouraging non-supported behaviors.

That said, I could certainly be convinced that the input format **should not** be in the spec, at which point requests like the one @rhpvorderman brings here are a mere implementation issue. 

I think this should be a more general discussion, and it's getting off the original topic of the issue. @patmagee what do you think the right venue is? A separate issue, email thread, something else?

**Comment by patmagee** [comment]
@geoffjentry the best place to discuss this would probably be the community mailing list, that or some individual makes able removing the requirement

**Comment by patmagee** [comment]
@geoffjentry I also think I misread the initial issue, hence the off-topic follow-up. I Read it as workflows should accept inputs as either `JSON` or as another format which the workflow engine defines and wdl is not too opinionated over that. I totally missed the part where we were talking about the engine functions. 

For the engine functions, allowing either `json` or `yaml` where json is supported seems like it would be unanticipated behavior for a function called `read_json`. I would not be strictly opposed to a `read_yaml` function if someone went ahead and made a PR for it

**Comment by rhpvorderman** [comment]
@geoffjentry @patmagee  thanks for your input. This issue I posted was not particularly well written. What I meant is that there is a need for a function that reads YAML in WDL. We have also discussed this internally and as @patmagee suggests this should not be included with the `read_json` function. I will go ahead and make a PR for a `read_yaml` function
