### ISSUE TITLE
add max/min operators

### ISSUE THREAD

**Issue by pshapiro4broad** [openwdl/wdl#276]
When writing WDL we sometimes need to compute min/max, e.g. when computing a value based on scatter, or computing VM size data based on input sizes. For example:
```
  # to account for the fact that the data is quite uneven across the shards.
  Int potential_hc_divisor = ScatterIntervalList.interval_count - 20
  Int hc_divisor = if potential_hc_divisor > 1 then potential_hc_divisor else 1
```
Having a builtin WDL function for this would make our WDL easier to read and maintain.

I would expect WDL to provide max and min for `Int` and `Float`, E.g. `Int max(Int, Int)` and `Float max(Float, Float)`

**Comment by pshapiro4broad** [comment]
This just came up again
```
  Int rounded_memory_size = ceil((if (rounded_bam_size > 10) then 10 else rounded_bam_size) * memory_multiplier)
  Int memory_size = if rounded_memory_size < 7 then 7 else rounded_memory_size
```

**Comment by geoffjentry** [comment]
Would you be interested in making a pull request against the spec?
