### ISSUE TITLE
String Interpolation SPEC Section Out-Of-Date

### ISSUE THREAD

**Issue by infispiel** [openwdl/wdl#285]
Hello,
In a conversation with a team developing a tool for WDL workflow analysis/linting/etc it has come to our attention that the String Interpolation section is out of date; my understanding is it is _preferred_ to use `~{}` rather than `${}`, but the String Interpolation section does not mention using `~{}` and it is resulting in some confusion.

**Comment by mlin** [comment]
cf. 
https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#string-interpolation
https://github.com/chanzuckerberg/miniwdl/issues/82

Also in need of explication, in addition to the recognized delimeters:
1. Are `sep`, `default`, etc. recognized in other-than-command interpolations?
2. That they can be used in workflows as well as tasks.

**Comment by jtratner** [comment]
I agree here - is it valid per-spec to use `~{variable}` in string interpolations outside of commands? I'm still not clear after reading spec + this ticket.

**Comment by patmagee** [comment]
Fixed in #229
