### ISSUE TITLE
Need for WDL regular release timeline.

### ISSUE THREAD

**Issue by rhpvorderman** [openwdl/wdl#294]
Dear all,

As a community we have been hacking on the SPEC for quite some time now. WDL 1.0 has been stable for quite a while. 

Currently there are a lot of nice new features in `development` and the diverge with WDL 1.0 grows ever wider. I think we could use a nice regular release schedule for the following reasons:

- Let me speak for myself. I want those new features. Now. So I am waiting for a new version to be released.
- With a regular schedule we can know when to expect a new feature to be present in the language.
- If the releases are few and far between, it will be harder to upgrade to the subsequent versions due to the sheer amount of changes.
- Every time a new version is released it is a chance to show off that this is truly a community project, and that many people have contributed to the spec. Encouraging others to do the same.

Therefore I propose we move to a half-yearly release schedule. Releasing each half year means:
- The spec won't move so fast that it cannot be tracked.
- The spec won't move so slow that you will never ever see those great new features implemented. (This is the current state :disappointed: )

Releasing three times a year also is a possibility.

I am looking forward to all your opinions on this.

**Comment by geoffjentry** [comment]
Hi @rhpvorderman This is probably best served over on the mailing list. Both because more people are likely to see it and also because this is really more of a structural question. I'm going to close this incarnation, can you repost over at `community@openwdl.org`?

**Comment by rhpvorderman** [comment]
@geoffjentry I could post a link to this discussion. Mailing-lists are **awful** for discussion. There will be so many e-mails generated that people will unsubscribe in droves.

I agree with you that this discussion needs more visibility. If you reopen the issue, I will link it on the mailing list.

**Comment by geoffjentry** [comment]
@rhpvorderman We explicitly want general discussion to happen on the mailing list and not via github issues. We can always have e.g. an "announcements" list if it really becomes an issue.

**Comment by rhpvorderman** [comment]
@geoffjentry I sent it to the list. Thank you for your fast replies.

**Comment by rhpvorderman** [comment]
@geoffjentry 
Shall I reopen this issue again (in a new issue)? The discussion here on Github is usually much livelier than the one we had on the mailing list.
