### ISSUE TITLE
Any interest in a Resource type?

### ISSUE THREAD

**Issue by DavyCats** [openwdl/wdl#299]
I was wondering if there is any interest in a Resource type. This type would function exactly the same way as a File, the only difference would be that the path to this file is interpreted the same way as the paths in an import: Relative to the wdl file, rather than the working directory. I feel this might be a useful addition in case you have some custom script or a configuration file for some program, which you would like to include in your workflow.

It probably wouldn't make sense to override such a type as an input, so maybe it wouldn't be allowed as an input?

For example, if your workflow directory looks like this:
```
my_workflow/
    my_workflow.wdl
    myFancyMetricsCollector.py
```
You could have a task like this:
```wdl
task collectSomeMetrics {
    input {
        File someDataFile
    }
    Resource script = "myFancyMetricsCollector.py"
    command {
        python ~{script} ~{someDataFile}
    }
    output {
        File metrics = stdout()
    }
}
```

**Comment by rhpvorderman** [comment]
Wouldn't this better be handled with a function?
```WDL
    File script = resource("myFancyMetricsCollector.py")
```
That way you do not have to add another file type. Anyway I am all for the general idea of enabling this sort of stuff.

**Comment by DavyCats** [comment]
@patmagee That's a good point about docker.

I do feel it's dangerous to leave the resolution of relative paths up to the execution engine. That seems like it would very easily make wdl files engine specific.

**Comment by patmagee** [comment]
@DavyCats it certainly would have that potential, however the work being done for tes and WES should solve that. It does specifically address this and makes a set of requirements for it. If we encourage adoption of those standards, or at least the principles the there should be no problem
