### ISSUE TITLE
Add Community Info to README

### ISSUE THREAD

**Issue by patmagee** [openwdl/wdl#325]
We should include links to the different mailing list on the README so new members can join.
At least the community@openwdl.org

**Comment by geoffjentry** [comment]
The README sucks. PRs welcome @patmagee ;)

**Comment by rhpvorderman** [comment]
Also [miniwdl](https://github.com/chanzuckerberg/miniwdl) should get a mention. I am willing to add this, if @patmagee is not already working on a PR. (Given his prolific writing of PRs I assume he is :wink: )

**Comment by patmagee** [comment]
@geoffjentry @rphvorderman this is mostly a reminder issue to myself to at some point come back and change the docs. Everyone is of course welcome to contribute!

**Comment by rhpvorderman** [comment]
A colleague of mine just started on wdl-aid. A python package that will autodocument WDL based on the information in parameter_meta. It uses miniwdl as a dependency.

https://github.com/biowdl/wdl-aid/tree/init 

I think it is very cool, so I will add this to the docs once we have a version on pypi.

**Comment by patmagee** [comment]
@rhpvorderman thats amazing its a bit like a linter!. I have seen a number of projects sprinnging up recently thanks to the work that @mlin and his team has done on miniwdl. 

@vdauwera @geoffjentry as I am looking into this, its clear to me that we are lacking a number of core updated features, namely an updated User Guide / How-To. I Remember you had mentioned that some of this will be ported from the current guide/support forum to Terra will this still be the case? I also wonder though whether we should have a minimum Getting Started and User guide directly within the `OpenWDL` repo in the wiki. I would be happy to help contribute to that

**Comment by patmagee** [comment]
@cjllanwarne is there a link somewhere to the `wdl4s` library? I know its been folded into the cromwell repo, but I am adding a section on language support/bindings and it would be great to include

**Comment by rhpvorderman** [comment]
I see the wdl-aid link is dead. Here is the new link: https://github.com/biowdl/wdl-aid/
And credit where it's due: @DavyCats made this nice package. And it would not have been possible without miniwdl. Thanks @mlin!

**Comment by patmagee** [comment]
attempted the update with #327
