### ISSUE TITLE
visual studio code highlighter is outdated

### ISSUE THREAD

**Issue by antonkulaga** [openwdl/wdl#328]
I noticed that code highlighting does not
![wrong struct](https://user-images.githubusercontent.com/842436/62767054-7f9a6480-ba9c-11e9-92ff-d230d16dc770.png)
 work properly for structs in Visual Studio Code

**Comment by geoffjentry** [comment]
@antonkulaga You should bring this up with the maintainer of the VSCode plugin, it's not maintained by OpenWDL
