### ISSUE TITLE
workflow/subworkflow namespacing in input JSON

### ISSUE THREAD

**Issue by mlin** [openwdl/wdl#329]
When we write workflow input JSON for Cromwell we precede the value name with the workflow name as the namespace, like `"wf.x": "foo"`. I always wondered a little why we have to put the workflow name there, but it's not a big deal.

There's a knock-on effect when a workflow calls another workflow, and the sub-workflow has an optional input we wish to supply. Then Cromwell expects *three* namespaces in the JSON key: workflow name, call name, and sub-workflow name `"wf.callname.subwf.x": "foo"`. In contrast, if the "callee" is a task rather than a workflow, we only have to write `"wf.callname.x": "foo"`. 

This syntax difference seems surprising given that no such distinction exists when we write `call callee { input: ... }` or refer to the call outputs in WDL. I can't think of any ambiguity solved by requiring the sub-workflow name there. The relevant [spec section](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#cromwell-style-inputs) doesn't seem to speak to this case.

Wondering if Cromwell team could comment on this, is there a specific rationale we should clarify in the spec or is it kind of just a historical path? @geoffjentry @cjllanwarne 

Based on @DavyCats https://github.com/chanzuckerberg/miniwdl/issues/193 which has a full example

**Comment by geoffjentry** [comment]
Not really the comment you were looking for @mlin - I need to actually form an opinion first :) However, this seems related to a few things from the past:

- #127 
- #192 
- #262

**Comment by DavyCats** [comment]
I would personally expect there to be no difference between the inputs for a sub-workflow or a task in the inputs JSON. As @mlin mentions, they are called in the same way in a WDL file, so I don't see any reason why inputs would have to be supplied differently. I'm sure there are implementation details I'm not aware of though.

**Comment by patmagee** [comment]
Closing this in favor of the discussion in the PR addressing this issue #340
