### ISSUE TITLE
large integer in input.json gives error

### ISSUE THREAD

**Issue by jfroula** [openwdl/wdl#330]
Not sure if this is a bug or not...but...
It seems like when my input.json file contains a very large number (Int), I get an error in cromwell 36.  For example, 7B fails but 700M works....see below to reproduce error.
If I use Float I get scientific notation which I then need to convert back to regular format.

# error
```
No coercion defined from '7000000000' of type 'spray.json.JsNumber' to 'Int'.
```

# Input.json
```
{
  "my_wf.largenumber": 7000000000
}
```

# wdl
```
workflow my_wf {
    Int largenumber

    call print_number {
        input: largenumber=largenumber
    }
}

task print_number {
    Int largenumber
    command {
        echo SOME_LARGE_NUMBER  ${largenumber}
    }
    output {
        String lnum=read_string(stdout())
    }
}
```

**Comment by geoffjentry** [comment]
Hi @jfroula - this is a Cromwell-specific bug and should be reported there.

**Comment by geoffjentry** [comment]
Specifically: https://github.com/broadinstitute/cromwell/issues
