### ISSUE TITLE
write_json doesn't seem to support Array[Object]

### ISSUE THREAD

**Issue by genomics-geek** [openwdl/wdl#339]
In the language specification [here](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#arrayobject-serialization-using-write_json), it seems to suggest that `write_json` could support `Array[Object]` types.

However, I get this error: 

```
Failed to process expression 'write_json(list)' (reason 1 of 1): 
Invalid parameter 'IdentifierLookup(list)'. Expected 'Object' but got 'Array[Object]'
```

This does not work:

```wdl
version 1.0

task WriteJSON {
  input {
    Array[Object] list = [{"test": 0}]
  }

  command {
    cat "~{write_json(list)}"
  }

  output {
    File output_json =  stdout()
  }
}


workflow WriteJSONWorkflow {
  call WriteJSON
}
```

Is this expected?  Thanks.

**Comment by geoffjentry** [comment]
If the spec describes this as being valid behavior but it's not working for you when you run it in an implementation, that'd be a bug on the part of the implementation (presumably Cromwell) and should be filed there

**Comment by patmagee** [comment]
closing this as a cromwell issues
