### ISSUE TITLE
Logo and other graphics

### ISSUE THREAD

**Issue by illusional** [openwdl/wdl#341]
Hi, just wondering if there's a graphics pack for WDL, and if there's not I think it would be beneficial for OpenWDL to provide the community with high resolution and vector graphics so it can be represented in posters.

I looked at the one from the website:

![wdl-bad-original](https://user-images.githubusercontent.com/22381693/69014415-21a3e400-09de-11ea-8b36-49bc512ad09d.png)

There's not a lot of symmetry between the shapes. The positions of the hexagons and the connections don't line up with consistency, and as it's not vectorised I can't scale it well.

![wdl-bad-annotated](https://user-images.githubusercontent.com/22381693/69014456-9ecf5900-09de-11ea-9605-1fc3e65ce9ca.png)

I whipped this vector one (rasterised for GitHub) up in Illustrator to try to address some of the symmetry, where:

- Uses: `#009abf` which is color matched from the original image, though the website uses `#3097ba`.  Comparison: top=`#3097ba`, bottom=`#009abf`: <img width="59" alt="wdl-color" src="https://user-images.githubusercontent.com/22381693/69014978-99c0d880-09e3-11ea-8a4a-31d8801779e9.png">

- `Courier` as the font (very very close to the original)
- The two left hexagons are separated by one side length and horizontally aligned
- Right hexagon is halfway between them, 
- The connection has a width of half a side-length

![wdl-new](https://user-images.githubusercontent.com/22381693/69014860-a7299300-09e2-11ea-9d1a-1840d0d609d7.png)

Here's a slight revision except the connections have padding on either side.

![wdl - connection](https://user-images.githubusercontent.com/22381693/69014862-ac86dd80-09e2-11ea-90b7-e5956263bbd2.png)

GitHub doesn't let me attach the SVGs here (unless I do it in a zip), but I'm more than happy to. I'm not a graphics designer by any means, but I thought these might be useful for the community.

**Comment by DavyCats** [comment]
I ran into this as well while making the BioWDL logo: ![BioWDL](https://biowdl.github.io/assets/img/logo.png)

This is the SVG I came up with, in case it might be helpful:
```svg
<svg viewBox="0 0 300 300">
  <defs>
    <symbol id="hex_with_tail">
      <polygon points="32.5,0 65,19 65,46 120,92.5, 107,100, 59,60 32.5,75 0,56 0,19"/>
    </symbol>
    <symbol id="hex">
      <polygon points="32.5,0 65,19 65,56 32.5,75 0,56 0,19"/>
    </symbol>
    <symbol id="strands">
        <use xlink:href="#hex_with_tail" x="0" y="0" fill="DarkSeaGreen"/>
        <use xlink:href="#hex_with_tail" x="-155" y="0" fill="PowderBlue"  transform="scale(-1,1)"/>

        <use xlink:href="#hex_with_tail" x="0" y="95" fill="PowderBlue"/>
        <use xlink:href="#hex_with_tail" x="-155" y="95" fill="DarkSeaGreen" transform="scale(-1,1)"/>

        <use xlink:href="#hex" x="0" y="190" fill="DarkSeaGreen"/>
        <use xlink:href="#hex" x="-155" y="190" fill="PowderBlue"  transform="scale(-1,1)"/>
    </symbol>
  </defs>
  <use xlink:href="#strands" x="72.5" y="15"/>
</svg>
```

**Comment by patmagee** [comment]
@illusional This is amazing... I would fully 100% support this change!

**Comment by patmagee** [comment]
@illusional can you please create a PR against this new Repo: https://github.com/openwdl/media and put the svg and different logo formats in a directory called `logo/`

**Comment by illusional** [comment]
Hey @patmagee, which logo do you want me to upload, the first (closer to original) or the second with more spacing?

**Comment by patmagee** [comment]
@illusional I personally like the second one, but maybe to err on a conservative side we can keep the minimally modified one for now as its more of a "cleanup" then an actual change, and wouldnt really need any sort of voting or discussion. We could always open another PR to potentially use the other one.

if its possible could you also add as a separate image, the logo to the left of the braces? I can update the GH repo image as well. I have no idea how much time you have, but inverse coloring would be a huge bonus. IE dark background, blue logo, white text :) 

this is phenominal thanks so much for the work!

**Comment by patmagee** [comment]
@illusional maybe with the brighter blue colors?

**Comment by geoffjentry** [comment]
Why not both and make that part of the discussion of the PR?

**Comment by patmagee** [comment]
Both seems like a good idea

**Comment by patmagee** [comment]
closing this in favor of https://github.com/openwdl/media/pull/1
