### ISSUE TITLE
Publish Changelogs with each new Version

### ISSUE THREAD

**Issue by patmagee** [openwdl/wdl#344]
In the process of trying to categorizer what PRs need to implemented as part of the "current' version, I realized that we have no easy way of seeing the changes that were introduced into the specification.. We should publish a changelog that minimally shows the PRs that were included.

To this end, I have started creating milestones (first for 2.0) that should help us track these things more easily.

Do people have any preferences on how the changelog should look, where it should live etc?

**Comment by rhpvorderman** [comment]
We usually include a `CHANGELOG.md` or `CHANGELOG.rst` in the root of the project. This is the [pytest-workflow one](https://github.com/LUMC/pytest-workflow/blob/develop/HISTORY.rst) ([raw version here](https://raw.githubusercontent.com/LUMC/pytest-workflow/develop/HISTORY.rst)).

To enforce this, including a PR template usually works. [Like this one](https://github.com/LUMC/pytest-workflow/blob/develop/.github/PULL_REQUEST_TEMPLATE.md). This will nag for every PR that there should be something in the changelog. This is surprisingly effective. We also do this for our BioWDL pipelines (such as [this one](https://github.com/biowdl/germline-DNA)) and [BioWDL tasks](https://github.com/biowdl/tasks).

We are happy the way this works. It is easy for developers to maintain and we hope it has some added value for the users. 

I am curious what other people prefer and use.

**Comment by DavyCats** [comment]
Since openWDL isn't using branches and tags to make releases, I wonder if it's the best option to put the changelog in the root. Since each version is given its own folder, perhaps these folders should include a changelog for each version?

I agree with @rhpvorderman that adding some PR template could be helpful for enforcement of the RFC process.

**Comment by patmagee** [comment]
@rhpvorderman @DavyCats these are both great suggestions. I like the Idea of the PR template alot, and am just wondering where makes sense for the CHANGELOG.. I initially had the same feeling as you @DavyCats, however It does not capture changes between versions...

**Comment by DavyCats** [comment]
That's a fair point. An alternative could also be to put the changelog inside of the spec itself. When a new version is made, the changelog is simply copied over (along with the rest of the spec). Each version will then list the differences between itself and the previous versions (but not future ones). One downside to this is that it will bloat an already large document.

I'm also fine with just putting one master changelog in the root of the repo or inside the /versions directory.

**Comment by rhpvorderman** [comment]
Since we are not maintaining a 1.0 branch but are continuously iterating on the develop spec, I think we can get away with using a master changelog in the root of the repository.
Also, after 2.0 there should not be any major version upgrades for a long time, preferably. So then a changelog in the root also makes sense.

**Comment by geoffjentry** [comment]
@rhpvorderman Keep in mind that due to SemVer, whether or not the next version is a major number is purely an artifact of if any accepted changes are backwards incompatible.

**Comment by geoffjentry** [comment]
@patmagee I'd keep it in the root. My intention was to make sure there was some full accounting of changes between 1.0 and 2.0, and so on and so forth going forward. It was just not really feasible leading up to 1.0 since we never really kept track of such things prior to that.
