### ISSUE TITLE
basename of a File? variable

### ISSUE THREAD

**Issue by freeseek** [openwdl/wdl#370]
I am trying to understand how to compute the basename of a File? variable

If I have a File? x variable and I try to compute:
```
basename(x)
```
I get the error:
```
Failed to process task definition '###' (reason 1 of 1): Failed to process expression 'basename(x)' (reason 1 of 1): Invalid parameter 'IdentifierLookup(x)'. Expected 'File' but got 'File?'
```
Ideally, I wanted to use the variable in a command section as follows:
```
command <<<
...
~{"--xxx " + basename(x)}
...
>>>
```
Instead the only ugly workaround I was able to find is this:
```
String x_not_optional = if defined(x) then x else ""
String opt_x = if defined(x) then "--xxx " + basename(x_not_optional) else ""
command <<<
...
~{opt_x}
...
>>>
```
Is there any more elegant and readable way?

**Comment by mlin** [comment]
`select_first([x])` is a way to cast `T?` to `T` failing at runtime if the value is null. A more obvious syntactic sugar for this would probably be well utilized.

BTW the [OpenWDL slack](https://openwdl.slack.com/) and/or [Bioinformatics StackExchange [wdl]](https://bioinformatics.stackexchange.com/questions/tagged/wdl) are great forums for quick questions like this

**Comment by freeseek** [comment]
So the most compact way I could think of is as follows:
```
command <<<
...
~{true="--xxx " false="" defined(x)} ~{basename(select_first([x, ""]))}
...
>>>
```
It is still a bit convoluted but much better than what I had guessed in the beginning. If you have an even more compact way I would love to know it. Otherwise I would consider this issue closed.

**Comment by mlin** [comment]
I think this should work:

```
~{"-xxx " + (if defined(x) then basename(x) else x)}
```

This uses the [special behavior of string concatenation inside interpolations](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#interpolating-and-concatenating-optional-strings) so that the whole expression evaluates to empty if the rhs is null.

**Comment by freeseek** [comment]
Actually, that gives error:
```
Failed to process task definition '###' (reason 1 of 1): Failed to process expression '("-xxx " + if defined(x) then basename(x) else x)' (reason 1 of 1): Invalid parameter 'IdentifierLookup(x)'. Expected 'File' but got 'File?'
```
But the following worked fine:
```
echo ~{"-xxx " + (if defined(x) then basename(select_first([x])) else x)}
```
And it is more compact. I find it odd to use `else x` though. Isn't there something like `else None` that can be used instead? What exactly is `x` when `x` is not defined?

**Comment by illusional** [comment]
There is a `None` in the development spec: https://github.com/openwdl/wdl/pull/263

**Comment by mlin** [comment]
You're right, my mistake on still needing `select_first`. At some point there was discussion of having the typechecking infer that `x` wouldn't be null there based on being in the consequent of `if defined(x) then ...`, but that hasn't yet been formalized.

**Comment by vdauwera** [comment]
#263 Was merged and is now part of the full spec. Does that resolve this issue? If not, is there a specific request that can be addressed to resolve this?

**Comment by patmagee** [comment]
closing this as it seems a viable solution was proposed and #263 was also merged
