### ISSUE TITLE
write_lines() exposes absolute paths that should not be visible to the docker running the task

### ISSUE THREAD

**Issue by freeseek** [openwdl/wdl#371]
Here is a very simple WDL (test.wdl):
```
version 1.0

workflow test {
  input {
    Array[File] list
  }

  call test {
    input:
      list = list
  }
}

task test {
  input {
    Array[File] list
    String docker = "ubuntu:20.04"
  }

  File lines = write_lines(list)

  command <<<
    cat ~{lines}
    cat ~{write_lines(list)}
    echo -e "~{sep="\\n" list}"
  >>>

  runtime {
    docker: docker
  }
}
```

Here is a basic input for the WDL (test.json):
```
{
    "test.list": ["/tmp/1", "/tmp/2", "/tmp/3"]
}
```

When I run the workflow on my laptop with the following command:
```
java -jar cromwell-51.jar run test.wdl -i test.json
```
I get the following stdout output:
```
/tmp/1
/tmp/2
/tmp/3
/cromwell-executions/test/00112233-4455-6677-8899-aabbccddeeff/call-test/inputs/1515144/1
/cromwell-executions/test/00112233-4455-6677-8899-aabbccddeeff/call-test/inputs/1515144/2
/cromwell-executions/test/00112233-4455-6677-8899-aabbccddeeff/call-test/inputs/1515144/3
/cromwell-executions/test/00112233-4455-6677-8899-aabbccddeeff/call-test/inputs/1515144/1
/cromwell-executions/test/00112233-4455-6677-8899-aabbccddeeff/call-test/inputs/1515144/2
/cromwell-executions/test/00112233-4455-6677-8899-aabbccddeeff/call-test/inputs/1515144/3
```
Which shows that the absolute paths of the files passed to the test workflow have been exposed. I cannot imagine this being the expected behavior. How do I get to have `write_lines(...)` behave more like `~{sep=" " ...}` even when it is not run inside a command <<< ... >>> instance?

**Comment by mlin** [comment]
To +1, miniwdl does produce "in-container" paths for `File`s evaluated in task declarations (that aren't outputs), this seemed necessary to enable usage such as the above, and I can't think of other usage served by producing host paths. This might be mostly a Cromwell implementation issue but also something where the WDL spec needs explication.

**Comment by freeseek** [comment]
Shall I repost this issue on https://github.com/broadinstitute/cromwell then?

**Comment by mlin** [comment]
I'd say yes because (agreeing with your original commentary) I can't think of a justification for binding a non-outputs task declaration to a host path, whereas binding to a container path is clearly useful. However, to the extent the WDL spec ought to clarify this point, it's also a valid issue here.

**Comment by mlin** [comment]
Linking https://github.com/broadinstitute/cromwell/issues/5540
