### ISSUE TITLE
WDL workflow testing

### ISSUE THREAD

**Issue by rdali** [openwdl/wdl#377]
I am rewriting our python workflows in WDL. These are long multi-step pipelines. To speed up development, I was wondering if there is a way to have a WDL "dry run"/pseudo-run to produce all the commands and resolve variables without execution? This will help speed up the process of development without having to wait for long testing times.
I am mainly interested in seeing the final command and input/outputs

**Comment by rhpvorderman** [comment]
I don't know if that is possible, but [miniwdl](https://github.com/chanzuckerberg/miniwdl/) has functionally to test a task separately. Also you can use `womtool validate` to check if the WDL has correctly connected the inputs and outputs.

As regards to the testing. I recommend [pytest-workflow](https://github.com/lumc/pytest-workflow). Which makes it really easy to write tests. If you use small test data most workflows shouldn't run a very long time. Our multi-step pipelines such as [our dna-seq pipeline](https://github.com/biowdl/germline-DNA) finish in 5 minutes.

Having a dry-run feature would be a quite interesting feature for the workflow runners indeed.

**Comment by patmagee** [comment]
@rdali this is not functionally possible as @rhpvorderman mentioned. The reason being that downstream tasks rely on the evaluated output of an upstream task. The only way to actually evaluate this is to run the command within a task.  The closest you can get at the moment, (which most execution engines do when static type checking) is ensuring the TYPES plumbed from one task to another are valid. But if a task has outputs and you want to test that the workflow produces said output, you will need to do a full run. [Cromwell](https://github.com/broadinstitute/cromwell) has [Call caching](https://cromwell.readthedocs.io/en/stable/cromwell_features/CallCaching/) which can help speed up run times in many cases.

One potential solution would be doing a dry run where the user can provide "Mock" outputs for a given task. But that functionality is not yet supported by any of the workflow engines.

**Comment by jdidion** [comment]
Seconding Ruben's recommendation of `miniwdl check`. We also have a new [toolkit](https://github.com/dnanexus-rnd/wdlTools) that includes a type.checker and linter (although both are currently beta-level). It could actually be possible to do incremental evaluation given a set of "typical" inputs, but that is not currently in-scope for wdlTools.

In addition to pytest-workflow, we also have [pytest-wdl](https://pytest-wdl.readthedocs.io/en/stable/) for writing WDL tests.

**Comment by rdali** [comment]
thank you guys. I created very very small test datasets as suggested and tested the pipeline in increments.
