### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by jdidion** [openwdl/wdl#379]
Hopefully I don't need to add context for this.

**Comment by rhpvorderman** [comment]
It should be a simple 
```
git checkout master
git pull origin master
git checkout -b main
git push origin main
```
Then make 'main', the main branch in settings.
Then switch all open pull requests to go to main.

I think you would need admin rights to pull this off. The change is so non-disruptive that I see no reason to wait.
Who has the powers to make this happen?

**Comment by rhpvorderman** [comment]
@jdidion I see you have already done all the work. Can you delete the master branch? That way people get an error if they try to do something like `git pull upstream master` in order to get the latest changes and make a new PR.

**Comment by jdidion** [comment]
Good point - I was keeping it around in case I made any kind of mistake, but I will delete it now.
