### ISSUE TITLE
use localized filenames for File inputs used in expressions in Non-Input Declarations

### ISSUE THREAD

**Issue by notestaff** [openwdl/wdl#381]
Currently, the spec says: "When a WDL author uses a File input in their **Command Section**, the fully qualified, localized path to the file is substituted into the command string."  But if a File input is used in an expression on the right-hand side of a non-input declaration, the substitution is not done.  Is there a reason for this?

**Comment by mlin** [comment]
cf. https://github.com/broadinstitute/cromwell/issues/5540 https://github.com/openwdl/wdl/issues/371

**Comment by jdidion** [comment]
Localized paths should also be used when evaluating private variables. If the spec doesn't already say this then we should add that explicitly.
