### ISSUE TITLE
Need help to modify parser.py file

### ISSUE THREAD

**Issue by Nitromon** [openwdl/wdl#382]
I want to add a rule that supports WDL files having a format:
`workflow xyz 
{
    input {abc}
}`

Since `$input` is not considered a `$wf_body_element`. I want to make changes to the parser.py but am unable to generate it using **Hermes Parser Generator** since I don't have the original grammar file to modify and input into the tool. May I get assistance on where to find it?

**Comment by jdidion** [comment]
versions/development/parsers/hermes

But if possible I'd recommend using the ANTLR4 grammar instead. You can use it to generate a Python parser http://blog.anvard.org/articles/2016/03/15/antlr-python.html

**Comment by Nitromon** [comment]
I was looking through the [grammar file](https://github.com/openwdl/wdl/blob/master/versions/1.0/parsers/hermes/grammar.hgr) and it shows `$inputs` in line 439: `    $wf_body_element = $call | $declaration | $while_loop | $if_stmt | $scatter | $inputs | $outputs | $wf_parameter_meta | $wf_meta`  but `$input` doesn't exist as `$wf_body_element` in parser.py line 733: `[
        "$wf_body_element = $call",
        "$wf_body_element = $declaration",
        "$wf_body_element = $while_loop",
        "$wf_body_element = $if_stmt",
        "$wf_body_element = $scatter",
        "$wf_body_element = $wf_outputs",
        "$wf_body_element = $wf_parameter_meta",
        "$wf_body_element = $wf_meta",]` so is the $input already included in 1.0? Because I was modifying another tool [wdl2cwl](https://github.com/common-workflow-lab/wdl2cwl) and the devs stated they used Wdl-Draft2, so would using WDL 1.0 solve my problem do I somehow need to add `$wf_body_element = $input` into parser.py?

Also, @jdidion thanks from the prompt reply

**Comment by Nitromon** [comment]
@jdidion Thanks for your prompt clarification.

I was looking through the grammar file and it shows `$inputs` in line 439: 
```
$wf_body_element = $call | $declaration | $while_loop | $if_stmt | $scatter | $inputs | $outputs | $wf_parameter_meta |$wf_meta
```

But `$inputs` doesn't exist as `$wf_body_element` in parser.py as per line 733: 
```
[
        "$wf_body_element = $call",
        "$wf_body_element = $declaration",
        "$wf_body_element = $while_loop",
        "$wf_body_element = $if_stmt",
        "$wf_body_element = $scatter",
        "$wf_body_element = $wf_outputs",
        "$wf_body_element = $wf_parameter_meta",
        "$wf_body_element = $wf_meta",
]
```
Seems like parser.py and grammar.hgr are out of sync. Am I missing something?

**Comment by jdidion** [comment]
Version 1.0 adds the input{} block. I would recommend using 1.0 if you're starting a new project.

**Comment by Nitromon** [comment]
Thanks for clarifying, @jdidion . I'll use the Ver 1.0 for my project then.
