### ISSUE TITLE
CONTRIBUTING broken links/update communication methods

### ISSUE THREAD

**Issue by vortexing** [openwdl/wdl#383]
The link in:
https://github.com/openwdl/wdl/blob/main/CONTRIBUTING.md... to the "developer's forum" is broken - also was this something prior to the Slack workspace or the gitter channel?

Then over in: https://github.com/openwdl/wdl/blob/main/RFC.md, does the mailing list still exist (it appears to not OR just requires additional logins so the link is sort of useless), and are you all still using the gitter channel?  Should all of these be updated to Slack?  OR some other method of communication that I just don't know about?  ;)

**Comment by patmagee** [comment]
Fixed by: 0522641
