### ISSUE TITLE
Import Tasks WDL Error (Newbie)

### ISSUE THREAD

**Issue by bol7asan** [openwdl/wdl#388]
I'm new to WDL but I think everything worked fairly until I've separated the tasks into different files. The tasks are in the same directory and not empty. I've attached the tasks for reference. The error i'm getting is :

`Could not build AST from workflow source. Source is empty or contains only comments and whitespace."`

 I'm validating the code with womtool-51.

```
#Import tasks
import "Alignment.wdl" as align
import "BW.wdl" as bw
import "checks.wdl" as ck
import "gets.wdl" as gt
import "mkDirs.wdl" as mk
import "PeakCalling.wdl" as pk
import "QC.wdl" as qc
import "SamToolsExtract.wdl" as ste



#ChIPseq main workflow

workflow ChIPseq{
	String refgenome #Reference genome
	Int numthreads
	String fastqfilesDirectory #Directory where all fastqfiles are contained
	String workingDirectory #Directory where all the analysis should be run
	
	call ck.checkServer { input: refgenome=refgenome} 
	
	call gt.GetSystemDirectories {
	input: fastqfilesDirectory = fastqfilesDirectory}

	#Run over each system seperately.
	scatter(directory in gt.GetSystemDirectories.fastqSystemDirectories){
		
		call gt.fastqPrefix { input: systemDirectory=directory}

		String analysisdir = "${workingDirectory}/Analysis/${gt.fastqPrefix.prefix}"
		call mk.createSTAR { input: analysisdir=analysisdir }
		call mk.createQCDir { input: analysisdir=analysisdir}
		call gt.nFastq { input: systemDirectory=directory}
		call ck.CheckQCFiles { input: fastqprefix=gt.fastqPrefix.prefix ,QCdir = mk.createQCDir.QCdir, nfastq=gt.nFastq.nfastq, analysisdir=analysisdir}
		call gt.ReverseandForward { input: systemDirectory=directory}
		call ck.SamFlag { input: systemDirectory=directory,analysisdir=analysisdir}
		if (ck.CheckQCFiles.QCcheck) {
			call fastQCT { input: rfastq=gt.ReverseandForward.rf[1], ffastq=gt.ReverseandForward.rf[0],numthreads=numthreads,QCdir=mk.createQCDir.QCdir,analysisdir=analysisdir}
		}
		if (!ck.CheckQCFiles.QCcheck){
			call fastQCF { input: QCdir=mk.createQCDir.QCdir,analysisdir=analysisdir }
		}
		
		call al.STARAlignment { input: genomedir=ck.checkServer.gd, numthreads=numthreads,ffastq=gt.ReverseandForward.rf[0],rfastq=

gt.ReverseandForward.rf[1], STAR=mk.createSTAR.STARd, analysisdir=analysisdir }
		call ste.ExtractPrimaryReads {
			input: STAR=mk.createSTAR.STARd, analysisdir=analysisdir,
			samflag=ck.SamFlag.samflag, numthreads=numthreads, ufBam=al.STARAlignment.unfilteredBam
		}
		call bw.BigWig {
			input: refgenome=refgenome,analysisdir=analysisdir,STAR=mk.createSTAR.STARd,numthreads=numthreads,rmdup=ste.ExtractPrimaryReads.rmdupSorted[0]}
		}
		call qc.BamQC { input: numthreads=numthreads ,analysisdir=analysisdir[0],STAR=mk.createSTAR.STARd[0], sorted=ste.ExtractPrimaryReads.rmdupSorted[1]}
		call pk.Peak { input: analysisdir=analysisdir[0], STAR=mk.createSTAR.STARd[0], sorted=ste.ExtractPrimaryReads.rmdupSorted[1]}
	}
```
[ChipSeqWorkFlow.zip](https://github.com/openwdl/wdl/files/4997797/ChipSeqWorkFlow.zip)

**Comment by rhpvorderman** [comment]
This is still in draft-2 WDL. Which is an incomplete spec. I do not know how well supported it is anymore.

Can you try to write it in WDL 1.0? It is a fairly easy modification. You only have to put `version 1.0` at the top of each file and provide an `input` section for each workflow and task. Simply put an `input { ... }` section around your variables.

Does that help?

Another thing that comes to mind is that you have all files opened in your IDE/editor, but that they have not been saved to disk yet.

**Comment by bol7asan** [comment]
Thank you. I've specified the version as 1.0 on top of each file and enclosed the inputs of with the `input { ...}`. I get another problem:

`Failed to process workflow definition 'ChIPseq' (reason 1 of 11): Cannot lookup value 'ck.CheckQCFiles', it is never declared. Available values are: ['fastQCF.__after', 'fastqPrefix.__after', 'ExtractPrimaryReads.__after', 'BigWig.__after', 'createSTAR.__after', 'ReverseandForward.__after', 'SamFlag.samflag', 'createQCDir.__after', 'ReverseandForward.rf', 'refgenome', 'workingDirectory', 'checkServer.gd', 'STARAlignment.__after', 'createQCDir.QCdir', 'createSTAR.STARd', 'checkServer.__after', 'ExtractPrimaryReads.rmdupSorted', 'Peak.__after', 'analysisdir', 'nFastq.nfastq', 'CheckQCFiles.__after', 'nFastq.__after', 'fastqPrefix.prefix', 'fastqfilesDirectory', 'GetSystemDirectories.__after', 'CheckQCFiles.QCcheck', 'STARAlignment.unfilteredBam', 'numthreads', 'BamQC.__after', 'SamFlag.__after', 'GetSystemDirectories.fastqSystemDirectories', 'fastQCT.__after']`

**Comment by DavyCats** [comment]
`ck.CheckQCFiles.QCcheck` should be `CheckQCFiles.QCcheck`, since the call isn't from the imported file, but the workflow itself.

Once a task gets called a new namespace will be created for that call inside the workflow, by default this call will have the same name as the task it calls (though you can change this using `as`). So when you call `ck.CheckQCFiles`, a new call is created called `CheckQCFiles`. This can that be used to retrieve the outputs of that call.

**Comment by rhpvorderman** [comment]
Okay I see the error: `if (ck.CheckQCFiles.QCcheck)` . If you call `ck.CheckQcFiles` it will become available in scope as `CheckQcFiles`. `ck.CheckQcFiles` refers to the **task**. `CheckQcFiles` to the **call**.

Some general advice (opinionated :wink:):
- `import "checks.wdl" as ck` why not `import "checks.wdl" as checks` ? `checks` is much easier to read than `ck`. Saving those 4 bytes in characters is *really not worth it*. Somebody else who has to read your workflow will hate you for it. That somebody else is probably you yourself in three months.
- In WDL you can alias calls as well: `call ck.CheckQCFiles as QCcheck` for example. This way you decide how a call is named, and you get rid of the implicitness in WDL.

**Comment by bol7asan** [comment]
Thank you guys @DavyCats @rhpvorderman. I totally agree with the naming, I wrote the code yesterday and got confused reading it today.
