### ISSUE TITLE
Allow String + Boolean concatenation

### ISSUE THREAD

**Issue by jdidion** [openwdl/wdl#390]
In previous WDL versions, concatenation of String to other primitive types was allowed, presumably to be used within placeholders. In development, those operations have been removed from the table. There is a new section on concatenation of optional strings during interpolation. I propose that, within placeholders, String + <other primitive> concatenation be allowed for both optional and non-optional operands.

Note: This issue has been modified.

**Comment by patmagee** [comment]
I think in most languages, all primitives can be ceorced to `String`.. (they might not be able to  Coerce back of course). Its strange how we do not allow this at all

**Comment by jdidion** [comment]
I'm not sure that is true. For example, in python this is illegal: `"a" + 1`.

There is a difference between automatic coercion to string and automatic string formatting.

**Comment by jdidion** [comment]
Sorry, forgot to check development spec. It looks like all the String + primitive entries have been removed from the operations table, and instead the section added on special handling of String concatenation during interpolation only. Does it make sense to allow string concatenation to any primitive type during interpolation?

**Comment by jdidion** [comment]
@patmagee I've updated the title and topic of this issue - you may wish to revoke your
