### ISSUE TITLE
Does WDL support optional outputs?

### ISSUE THREAD

**Issue by yfarjoun** [openwdl/wdl#394]
I see the section about optional inputs...with lots of nice examples and explanations....but I do not see a similar section about optional outputs

https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#outputs-section

womtool (at least) thinks that outputs can be marked as optional, but Cromwell doesn't support that....the spec is inconclusive...

where the spec does talk about Optional types, it seems very biased about "inputs": https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#optional-parameters--type-constraints 

Even though optional types can be used throughout a wdl script and not only in the input section. 

I think it would be good if the spec were more consistent about Optional types, and ideally, make sure to have examples and wording that supports a parameter having an optional type in all stages of the script (workflow input, task input, workflow variable, task output, workflow output).

**Comment by DavyCats** [comment]
If I'm not mistaken cromwell does support optional outputs, just not on certain backends. 

In the development spec, the section on [optional literals](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#optional-literals) doesn't specifically mention inputs and there are examples of optionals being used outside of the input section (eg. in the [conditionals](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#conditionals) section). There indeed don't appear to be any examples of optionals in the output sections. I'd agree that it might be good to add something there.

**Comment by yfarjoun** [comment]
true dat. but a different section says this: "A user does not need to specify a value for the parameter in order to satisfy all the **inputs** to the workflow."

**Comment by patmagee** [comment]
@yfarjoun have you seen t his? https://github.com/openwdl/wdl/pull/310

**Comment by jdidion** [comment]
This is covered by the 1.1 spec.
