### ISSUE TITLE
Feature request: setting runtime attributes at runtime #5855

### ISSUE THREAD

**Issue by pieterlukasse** [openwdl/wdl#401]
Hi, 

I would like to be able to override something like:

```
    runtime {
        docker: "mydockerimagename"
    }
```
at runtime. Is this possible already? I know people have been using workarounds by making the docker image name to be an input variable. I would like to have it separate from workflow input variables though.

**Comment by DavyCats** [comment]
I believe this is being addressed as part of #315.

**Comment by jdidion** [comment]
I believe this is something that would have to be implemented by the runtime engine.

@pieterlukasse what specifically would you add to/change in the spec?

**Comment by jdidion** [comment]
I guess one possibility is that since `runtime` is a reserved word, the attributes could be overridden in the input file 

```
"<task>.runtime.container": "ubuntu"
```

**Comment by jdidion** [comment]
Ah, and now I see that's exactly what #315 specifies😁

**Comment by pieterlukasse** [comment]
Yes, thanks! More specifically here https://github.com/openwdl/wdl/pull/315/files#diff-7ab1be25d3b4d9ecf4f763e14d464681R3029 

This is great news. What are the plans for implementing this? I guess that is again a question for the Cromwell team...

**Comment by patmagee** [comment]
@pieterlukasse as always, it will be up to the engines. If you have the scala chops you could always submit a PR to help them get there faster, (or miniwdl or dxwdl for that).
