### ISSUE TITLE
squote() is in the spec but appears to have never been implemented

### ISSUE THREAD

**Issue by aofarrel** [openwdl/wdl#403]
I have three WDL arrays generated via scattered tasks.
* Array[String] containing filenames 
* Array[Int] containing read length
* Array[Float] containing coverage

In attempt to print the contents of the arrays to a _single_ output file rather than a glob of multiple output files, I attempted to convert them to Python arrays and iterate through them with Python. (If there is a way to iterate through an array within a task natively in WDL, please let me know.) Because the conversion of the string array did not have quotation marks around the characters in the string, it would be invalid in Python -- ie, instead of ["foo.cram", "bar.cram"] it would create [foo.cram, bar.cram]. To get around this, I tried to use squote() as described on the WDL spec, as according to the spec, that would surrounding the strings with single quotes, which I figued would result in a valid Python list, ie, ['foo.cram', 'bar.cram']. Eventually I realized squote() is on the spec but isn’t actually implemented. I suspect it may have been one of the “lies” that got missed during the updating of the spec to WDL 1.0, and this may also apply to similar functions such as quote().

For example, if this is put in the command section, exactly how it's written in the spec, it results in an error at runtime.
```
		Array[String] env = ["key1=value1", "key2=value2", "key3=value3"]
		Array[String] env_quoted = squote(env)
```
Conversely, if this is put in an in input or output section, this will result in an immediate error due to unknown engine function. After a quick check of what @dailydreaming and I could find, it seems that squote() does not exist in any Cromwell-related code, expect perhaps miniwdl.

It would indeed be a useful function, but if it doesn’t exist, it shouldn’t be in the spec, and this may indicate the spec needs to be looked over again.

**Comment by mlin** [comment]
`squote()` wasn't part of the WDL 1.0 spec. The working "development" version of the spec on the other hand is a moving target. `squote()` was "just" added [earlier this year](https://github.com/openwdl/wdl/pull/362) and Cromwell hasn't caught up to that bit yet. (Conversely there are significant parts of the development spec which Cromwell implements and miniwdl doesn't yet.)

**Comment by jdidion** [comment]
It is implemented in wdlTools

**Comment by jdidion** [comment]
This is a Cromwell issue, not WDL.
