### ISSUE TITLE
reading array of objects

### ISSUE THREAD

**Issue by matthdsm** [openwdl/wdl#409]
Hi,

I have a script that outputs an array of objects, which I need to use as input for a workflow step.
The array is formatted as:
```json
[
    {"samplename": "XXX", "files":[ "XXX_L1.bam", "XXX_L2.bam", ...]}
]
```
from which I would need `Array[Object[String,Array[File]]]` as parsed output.

- I've tried parsing to tsv an using `read_objects`, but that reads the `files` array as single string
- I've tried using Array[struct] as output type with `read_objects` and `read_json`, but that yields ` No coercion defined`
- I've tried using a `Map`, which worked, but is useless in my case, since it can't be scattered.

Any suggestions on how to format and/or parse my data so I get a result with the correct datatypes thats able to be scattered?

Thanks
M

**Comment by DavyCats** [comment]
I believe read_json would work if you wrap the array in a struct:

So the generated JSON file will look like:
```json
{"samples": 
  [
    {"samplename": "XXX", "files":[ "XXX_L1.bam", "XXX_L2.bam", ...]}
  ]
}
```

And the WDL something like:
```wdl
version 1.0

struct Sample {
    String samplename
    Array[File] files
}

struct Wrapper {
    Array[Sample] samples
}

workflow wf {
    [...]
    call script {}
    Wrapper samples = read_json(script.output_json)
    scatter (sample in samples.samples) {
        [...]
    }
}

```

**Comment by matthdsm** [comment]
Hi @DavyCats,

Thanks for the reply! 
Just a small caveat, the output is an array of json objects, not one json object containing an array.

To be sure, I've tried your solution, and sadly it doesn't seem to work 😞. I'm getting the message there are no values specified for `samplename` and `files`.

Any more ideas?

Thanks
M

**Comment by DavyCats** [comment]
So it's not possible to change the layout of the JSON file?

At BioWDL we use the strategy I described above: https://github.com/biowdl/RNA-seq/blob/develop/RNA-seq.wdl#L85 (see also https://github.com/biowdl/RNA-seq/blob/develop/structs.wdl)

There are several issues open on the cromwell github about reading arrays using `read_json`, but it doesn't look like there has been any recent progress there: https://github.com/broadinstitute/cromwell/issues/4518, https://github.com/broadinstitute/cromwell/issues/4219

**Comment by matthdsm** [comment]
I've changed the layout of the json, but still no dice. I'm currently trying to further pinpoint the issue.

Thanks again.
M

**Comment by matthdsm** [comment]
To further clarify what I'm trying to do here:
We're creating a workflow to demultiplex Illumina bcl's to uBam using Picard. The downside here is that Picard creates files per lane.
I'm trying to merge the uBam's/sample/lane into 1 uBam/sample, based on the the sample name in de filenames.

Nothing's written in stone, and everything can still be changed if something comes up. I've got the demultiplexing thing down, but I'm stuck on the merging step. I have the tooling, but am struggling with coordinating the WDL around it.

M

**Comment by matthdsm** [comment]
Full disclosure:

wf (checked using womtool):
```wdl
version 1.0

struct UnalignedSample {
    String id
    Array[File] unaligned_bams
}

workflow wf {
    input {
        Array[File] unaligned_bams
    }
    call ParseUnalignedBamFilenames {
        input:
            unaligned_bams = unaligned_bams
    }
    scatter (unaligned_sample in ParseUnalignedBamFilenames.unaligned_samples_list){
        call Print {
            input:
                in = unaligned_sample.id
        }
    }
}

task ParseUnalignedBamFilenames {
    input {
        Array[File] unaligned_bams
        File script = "scripts/ParseUnalignedBamFileNames.py"
    }

    command {
        python ~{script} ~{sep=" " unaligned_bams}
    }

    output {
        Array[UnalignedSample] unaligned_samples_list = read_json(stdout())
    }

    runtime {
        #docker: python:3
        cpu: 1
    }
}

task Print{
    input {
        String in
    }
    command {
        echo ~{in}
    }
    output {
        String out = read_lines(stdout())
    }
}
```

`unaligned_samples_list` json:
```json
[
  {
    "id": "CFD1901315",
    "unaligned_bams": [
      "./test_input/CFD1901315.unaligned.bam"
    ]
  },
  {
    "id": "CFD1901317",
    "unaligned_bams": [
      "./test_input/CFD1901317.unaligned.bam"
    ]
  },
  {
    "id": "CFD1901318",
    "unaligned_bams": [
      "./test_input/CFD1901318.unaligned.bam"
    ]
  },
  {
    "id": "CFD1901319",
    "unaligned_bams": [
      "./test_input/CFD1901319.unaligned.bam"
    ]
  },
  {
    "id": "CFD1902451",
    "unaligned_bams": [
      "./test_input/CFD1902451.unaligned.bam"
    ]
  },
  {
    "id": "CFD1902452",
    "unaligned_bams": [
      "./test_input/CFD1902452.unaligned.bam"
    ]
  },
  {
    "id": "CFD1902454",
    "unaligned_bams": [
      "./test_input/CFD1902454.unaligned.bam"
    ]
  },
  {
    "id": "CFD1902455",
    "unaligned_bams": [
      "./test_input/CFD1902455.unaligned.bam"
    ]
  },
  {
    "id": "Undetermined",
    "unaligned_bams": [
      "./test_input/Undetermined.unaligned.bam"
    ]
  }
]
```

And finally, the cromwell output:
```sh
Bad output 'ParseUnalignedBamFilenames.unaligned_samples_list': Failed to read_json(".../call-ParseUnalignedBamFilenames/execution/stdout") (reason 1 of 1): No coercion defined from '[{...},{...}]' of type 'spray.json.JsArray' to 'Object'
```

I'm lost....

M

**Comment by rhpvorderman** [comment]
Hi. `read_json` has a bug, and it does not read arrays.
You could make a struct
```
struct unaligned_bams {
      Array[unalignedBam] bams
}
```
Adapt your json accordingly and read that in.
I know it is not ideal, but this is  a workaround for that bug.

This is how we set up structs in our pipeline: https://github.com/biowdl/germline-DNA/blob/develop/structs.wdl

**Comment by jdidion** [comment]
This is a Cromwell bug, right? Shouldn't this issue be in the Cromwell Jira instead of here?

**Comment by matthdsm** [comment]
Fixed by writing to a json file/sample, scattering over the array of files and  reading the json.
Thanks for all the comments!

Cheers
M
