### ISSUE TITLE
Suggestion: new tool for documentation, wdldoc

### ISSUE THREAD

**Issue by a-frantz** [openwdl/wdl#410]
We've created a command line tool for generating Markdown for wdl files that's more comprehensive than the other tools we tried.

I think it would be useful for other developers, and could be linked to in the "Parsers and Language Support" section.

Feel free to check out the repo! https://github.com/stjudecloud/wdldoc

Depending on user feedback, we may add support for other mark up languages in the future, or more granular formatting options.

**Comment by patmagee** [comment]
Hey @a-frantz thanks so much for posting this! I look forward to trying it out!

**Comment by vdauwera** [comment]
Hey this is awesome, going to show this to our Pipelines and Docs teams

**Comment by vdauwera** [comment]
What do we need to do for the purpose of closing this issue? Can we find a good place in the docs to reference this?

**Comment by patmagee** [comment]
hmm, we could add a new `Documentation Generation` section to the front page and the website?

**Comment by vdauwera** [comment]
Under "Software and Tools" you mean? I'd be on board with that

**Comment by patmagee** [comment]
@vdauwera did you want to make that change or would you like me?

**Comment by vdauwera** [comment]
Whoops feel free to go ahead and do it @patmagee — I was briefly on a WDL holiday but got pulled back by a wave of other stuff.

**Comment by patmagee** [comment]
added!
