### ISSUE TITLE
syntax question: get array of values from array of objects

### ISSUE THREAD

**Issue by matthdsm** [openwdl/wdl#420]
Hi,

I've got an array of structs
```wdl
struct LaneDefinition {
    Int lane_number
    String read_structure
    File barcode_file
    File library_params
}
```
from which I'd need to extract an `Array[File]` from the `library_params` key. Whats the correct syntax to achieve something like this? Do I need an extra task or is this supported somehow?

Thanks
M

**Comment by DavyCats** [comment]
I haven't tried this, but I image this would work:

```wdl
#arrayOfLanes is an Array[LaneDefinition]
scatter (lane in arrayOfLanes) {
    File library_params = lane.library_params
}
```
Since `library_params` gets defined inside a scatter, it becomes an array outside of it.

**Comment by matthdsm** [comment]
Seems to validate allright! Thanks for the tip!

Cheers
M
