### ISSUE TITLE
Clarify nested string interpolations

### ISSUE THREAD

**Issue by jdidion** [openwdl/wdl#425]
The specification should state explicitly that nested string interpolations are allowed, and provide an example. Currently, the grammars (Hermes and ANTLR4) allow for infinite nesting. I am fine with this, or with setting some kind of limit - personally, I don't see why it should be necessary to nest deeper than one level but I'm happy to see a counter-example.

**Comment by mlin** [comment]
Fairly recently I added [a few test cases](https://github.com/chanzuckerberg/miniwdl/commit/fb414e0d056cc176e7c88b0548d20fb5cd232f8a) for nested interpolations in miniwdl. (I was surprised that they worked -- it was by accident!). One level of nesting sounds fine to me too.

**Comment by patmagee** [comment]
When I made the initial grammar, Infinite recursion was actually the goal based on what I understood the existing behaviour of cromwell to be at the time. If its not an undue burden, I would say we just allow this

**Comment by patmagee** [comment]
@jdidion is there anything else that you need from this issue or can it be closed?
