### ISSUE TITLE
How do I rename output folder created using glob (WDL-Cromwell)?

### ISSUE THREAD

**Issue by mariadelmarq** [openwdl/wdl#427]
I made a wdl task for fastqc that outputs the zip files, of which there will be as many as reads that the sample I'm working on at that moment has. We create the output using glob:

  output {
    Array[File] fastqcArray = glob("*.zip")
  } 
I would like to give the folder a name that is representative of what it contains, for example `fastqc`, rather than glob-xxxxxxx, so that it's clear what it is in my task's output folder. Is this possible, and if so, how can I achieve it?

**Comment by rhpvorderman** [comment]
Yes it is possible. Take a look at the [biowdl tasks repository](https://github.com/biowdl/tasks). There is a [FastQC task](https://github.com/biowdl/tasks/blob/d1e2d6e56131432ea941722aa1b6ac3527d2b02d/fastqc.wdl#L23) in there that knows the path of the zip.

**Comment by mariadelmarq** [comment]
Thanks, @rhpvorderman. I'm very new to wdl, so I apologise in advance if I'm missing something.

My fastqc task works well, and only collects the output that I want to use (the .zip files for each file of reads). I'm using Cromwell as the scheduling engine, and that means that the intermediate output folders for each of my sub-tasks (such as this fastqc one) ends up somewhere inside ./cromwell-executions/\*/.../\*/execution. By setting `"use_relative_output_paths": true` (as in https://cromwell.readthedocs.io/en/stable/wf_options/Overview/#output-copying), I have been able to nicely organise the structure of the output folder for the main wdl task, which itself calls all of the other sub-tasks. That is, for all outputs EXCEPT those created in the output section of the wdl files using glob. Those get placed into a folder ./cromwell-executions/\*/.../\*/execution/glob-{unique_id}, and therefore, when copied into my main output folder by cromwell, retain the non-specific glob-{unique_id} name.

I am looking for way to rename that glob-{unique_id} folder to "fastqc" or something else of the sort in my main output folder. I hope that is clearer!

**Comment by rhpvorderman** [comment]
> Thanks, @rhpvorderman. I'm very new to wdl, so I apologise in advance if I'm missing something.

No need to apologize. We are all new to a language at some point :). 

> By setting "use_relative_output_paths": true (as in https://cromwell.readthedocs.io/en/stable/wf_options/Overview/#output-copying), I have been able to nicely organise the structure of the output folder for the main wdl task, which itself calls all of the other sub-tasks. 

> I am looking for way to rename that glob-{unique_id} folder to "fastqc" or something else of the sort in my main output folder. I hope that is clearer!

We do the same thing in BioWDL. I think the solution is to run only **one** fastq task per sample. You can use the `scatter` directive to run a task over a `Array[File]` or other arrays. If you have only one fastq in your FastQC job, it is possible to predict the output path, which is why I was referring to the FastQC task earlier. [On this line](https://github.com/biowdl/tasks/blob/d1e2d6e56131432ea941722aa1b6ac3527d2b02d/fastqc.wdl#L59) you can see the regex that finds the output folder based on the input name. 

Another advantage of running multiple FastQC tasks instead of one that processes all fastqs, is that your workflow becomes way more scalable when working with a cloud or hpc backend.

**Comment by mariadelmarq** [comment]
@rhpvorderman: thank you SO much! I finally managed to get my head around what you wrote (with the help of a colleague 😜). This is what I went with in the end (simplified), in case somebody else ever finds this issue in the future:
```
task fastqc_task {
  File forwardReads
  File reverseReads
  String fwdName = sub(basename(forwardReads),".f.*q.*$","")
  String revName = sub(basename(reverseReads),".f.*q.*$","")
  command {
    mkdir -p ./qc/fastqc_zip
    fastqc ${forwardReads} ${reverseReads} --outdir ./qc/fastqc_zip
  }
  output {
    Array[File] fastqcArray = ["./qc/fastqc_zip/${fwdName}_fastqc.zip", "./qc/fastqc_zip/${revName}_fastqc.zip"]
  } 
}
```
Then my files end up nicely organised in my output folder, under qc -> fastqc_zip. Thanks again, and I'll close this issue now 👍  Cheers!
