### ISSUE TITLE
string interpolation of compound types

### ISSUE THREAD

**Issue by notestaff** [openwdl/wdl#430]
The spec for [string interpolation](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#string-interpolation) says "Any ${identifier} inside of a string literal must be replaced with the value of the identifier".   What is the specified behavior when the value is a compound type?   In Cromwell 54, it seems that in expressions for intermediate values, identifier gets substituted with a string printout of the compound value (which is implementation-dependent?  or is guaranteed to be a valid compound literal?) , but within task command sections this does not work.  Is the current behavior for intermediate values (which is quite useful) an undocumented feature that may break in later versions, or part of the spec?  Thanks for help!

**Comment by jdidion** [comment]
It may be helpful to read the relevant sections on string interpolation from the draft 1.1 spec:

* https://github.com/openwdl/wdl/blob/v1.1/versions/1.1/SPEC.md#expression-placeholders-and-string-interpolation
* https://github.com/openwdl/wdl/blob/v1.1/versions/1.1/SPEC.md#expression-placeholders

"...ultimately, the value of the placeholder must be converted to a string. This is immediately possible for primitive values, but compound values must be somehow converted to primitive values. In some cases, this is not possible, and the only available mechanism is to write the complex output to a file."

There is an Appendix that provides methods and examples for serializing and deserializing non-primitive values: 
* https://github.com/openwdl/wdl/blob/v1.1/versions/1.1/SPEC.md#appendix-a-wdl-value-serialization-and-deserialization

**Comment by notestaff** [comment]
@jdidion Thanks.  The draft 1.1 spec is explicit that "Compound types cannot be implicitly converted to strings" in any interpolation.  This makes sense in conjunction with other changes, like the addition of the `sep` function.   Do you know if the intent of the 1.0 spec was to permit implicit conversion of compound types to strings during interpolation where `sep` is not supported, such as in expressions for intermediate values?

**Comment by jdidion** [comment]
I don't think the intention was ever to support implicit conversion of compound values, but like many things it was not explicit in the 1.0 spec. We're trying to find and fix as many of those ambiguities as possible in 1.1 and future versions.

**Comment by illusional** [comment]
I implemented `sep` as it means you could use arrays of strings except where you were explicitly binding them to a command line. I found issues with interpolation options in embedded strings within Cromwell. Additionally, it was the only functionality that was still restricted by the interpolation block, every other option could be performed using simple WDL.

**Comment by patmagee** [comment]
Since this is clarified in 1.1 I am closing this
