### ISSUE TITLE
How to handle array of files for workflow when 1 is required but other are optional

### ISSUE THREAD

**Issue by BJWiley233** [openwdl/wdl#433]
I get a coercion issue when I have a workflow that requires 1 known_sites files but the rest/more are optional.  How do I pass that as array to a task?

Ex.
```
File? gnomad # need at least 1 known-sites file
File? gnomad_idx
File? mills
File? mills_idx
File? known_indels
File? known_indels_idx

call md_bqsr.bqsr as bqsr {
input :
    known_sites = [gnomad, mills, known_indels],
    known_sites_idx = [gnomad_idx, mills_idx, known_indels_idx],
    runtime_params = standard_runtime
}

task bqsr {
    input {
        Array[File]+ known_sites
        Array[File]+ known_sites_idx
...

```

I get `Cannot coerce expression of type 'Array[File?]+' to 'Array[File]+'`.  Also I am new to WDL obviously.  The documentation is good for starters but this kind of stuff is not in there.  How do I get support for these questions.  Is it still fairly new that Google searches return little?

**Comment by DavyCats** [comment]
You can use the [select_all](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#arrayx-select_allarrayx) function to turn an `Array[X?]` into an `Array[X]`, so your call would end up looking like this:

```wdl
call md_bqsr.bqsr as bqsr {
  input :
    known_sites = select_all([gnomad, mills, known_indels]),
    known_sites_idx = select_all([gnomad_idx, mills_idx, known_indels_idx]),
    runtime_params = standard_runtime
}
```

As to where to get support, there are some places where one can look for help mentioned in the [README](https://github.com/openwdl/wdl#community-and-support).

Hope this helps :)

**Comment by BJWiley233** [comment]
Thanks Davy,

I will either post to Slack or on Stackexchange using 'wdl' tag future questions.
