### ISSUE TITLE
non-fragment lexer rule BeginWhitespace can match the empty string

### ISSUE THREAD

**Issue by yunhailuo** [openwdl/wdl#439]
Got the following warning when trying to use antlr4 tool (4.9.1) to generates a parser from WDL v1.1:
```
warning(146): WdlV1_1Lexer.g4:118:0: non-fragment lexer rule BeginWhitespace can match the empty string
```

Checked this line: https://github.com/openwdl/wdl/blob/main/versions/1.1/parsers/antlr4/WdlV1_1Lexer.g4#L118 and wondering if the rule there should actually `+` instead of `*`:
```
BeginWhitespace: [ \t\r\n]+ -> channel(HIDDEN);
```

**Comment by jdidion** [comment]
I believe you can ignore this. At least it has not (yet) been the source of any bugs in wdlTools. Feel free to submit a PR if you figure out how to change the grammar to get rid of it.

**Comment by yunhailuo** [comment]
> I believe you can ignore this. At least it has not (yet) been the source of any bugs in wdlTools. Feel free to submit a PR if you figure out how to change the grammar to get rid of it.

I think matching empty string is not a desired behavior for the `BeginWhitespace` lexer rule. So I PRed: https://github.com/openwdl/wdl/pull/440 . But your are definitely right. This is just a warning and doesn't really break anything.

**Comment by jdidion** [comment]
Thanks! I've approved the PR.
