### ISSUE TITLE
How to compare an empty value with None for optional types

### ISSUE THREAD

**Issue by Sea0310** [openwdl/wdl#442]
```
Int? x
Int? y = None
Int z = 1
Int? x1

Boolean b = x == y // true or false?
Boolean b = x == z // true or false?
Boolean b = x == x1 // true or false? 
```
@jdidion

**Comment by rhpvorderman** [comment]
x in this case defaults to `None` (I think). Same with x1. So I think the cases are 
`None == None`: true
`None == 1`: False
` None == None`: true

But of course there is also the case:
```wdl
Int? x
String? y

Boolean b = x == y
```
Can a `None` string be compared to a `None` int?

Is `None` equal to `None`?

**Comment by jdidion** [comment]
@rhpvorderman I concur with your answers. 

As for comparing `Int?` to `String?` - this is not allowed and should result in an error. `Int == String` is not one of the supported binary operations (https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#binary-operators-on-primitive-types) and `Int<->String` is not one of the supported automatic type conversions (https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#type-coercion).
