### ISSUE TITLE
Programmatically generate WDL?

### ISSUE THREAD

**Issue by nyue** [openwdl/wdl#445]
Are there any programming API to generate WDL?
I am looking for something that is currently supported and maintained.

Cheers

**Comment by jdidion** [comment]
wdlTools (Scala) enables you to create a WDL document using case classes and then write it to text using a code formatter.

https://github.com/dnanexus-rnd/wdlTools

**Comment by nyue** [comment]
@jdidion thanks for the info about the wdlTools project.

Is there a particular Scala example which illustrate the creation and writing out of WDL files in the wdlTools project, I can't seems to find one in the wdlTools git repo.

Cheers

**Comment by vdauwera** [comment]
@nyue FWIW the GATK devs have a way to auto-generate WDLs for individual tools based on Java annotations, check out https://github.com/broadinstitute/gatk-tool-wdls if John's pointer to wdlTools doesn't meet your needs.

**Comment by matthdsm** [comment]
[Janis](https://janis.readthedocs.io/en/latest/) is also a great tool to write WDL in python.
Developed by @illusional

**Comment by patmagee** [comment]
@nyue is there an interest in parsing the WDL's as well into specific language bindings as well?

**Comment by jdidion** [comment]
@nyue sorry this took so long - here is an example https://github.com/dnanexus-rnd/wdlTools/blob/develop/doc/Examples/GenerateCode.scala

You can see right now that it is quite verbose to write this code. Our current use case for the code generator is to upgrade from older to newer versions of WDL, so we are only ever generating from an AST parsed from from another WDL file. If generating from hand-coded AST is going to be an important use-case then we can look at improving the ergonomics. Feel free to open an issue with any suggestions.

**Comment by jdidion** [comment]
I am going to close this issue as it seems there are a few options proposed for generating WDL. @nyue if you are interested in continuing the discussion, please open a new thread in [Discussions](https://github.com/openwdl/wdl/discussions).
