### ISSUE TITLE
Mixing tasks run in docker and locally

### ISSUE THREAD

**Issue by matthdsm** [openwdl/wdl#452]
Hi,

I'm not sure if this is the right place to ask this, but I suppose the biggest WDL knowledge base is here.

## context
I trying to run a workflow using cromwell + docker-in-slurm. This works great for all general tasks, but my workflow has the following lines

```
....
    scatter (unaligned_bam in unaligned_sample.unaligned_bams) {

        Float unaligned_bam_size = size(unaligned_bam, "GiB")
        String unaligned_bam_basename = basename(unaligned_bam, ".unaligned.bam")

        if (unaligned_bam_size <= cutoff_for_large_rg_in_gb) {
            call mapping.SamToFastqBwaMemMergeBamAlignments_PairedEnd as mapping {
                input:
                    input_bam = unaligned_bam,
                    output_bam_basename = unaligned_bam_basename,
                    bwa_reference = bwa_reference,
                    sample_name = unaligned_sample.sample_name,

                    num_cpu = num_cpu
            }
        }
        if (unaligned_bam_size >= cutoff_for_large_rg_in_gb) {
            call mapping.SamToFastqBwaMemMergeBamAlignments_PairedEnd_LargeReadGroup as mapping_large_rg {
                input:
                    input_bam = unaligned_bam,
                    output_bam_basename = unaligned_bam_basename,
                    bwa_reference = bwa_reference,
                    sample_name = unaligned_sample.sample_name,

                    num_cpu = num_cpu
            }
        }

        File aligned_bam = select_first([mapping.output_bam, mapping_large_rg.output_bam])
    }
....
```

Where `unaligned_bam` is a struct, which is read from a json file.
```
struct UnalignedSample {
    String sample_name
    String sample_basename
    Array[File] unaligned_bams
}
```
In this context, the `Array[File] unaligned_bams` is essentially a file-of-filenames.

## Actual issue
My issue is that the filepaths in the array are relative to the docker root, so the files aren't found when the call to `size(unaligned_bam, "GiB")` is made. This step is kind of important in the decision tree for the workflow.
The flow was inspired by [the broad WARP workflows](https://github.com/broadinstitute/warp/blob/a0ed985fddb710b735fd0fc2783e3c37e529c30e/tasks/broad/UnmappedBamToAlignedBam.wdl#L70)

Any idea how I could fix this?

**Comment by patmagee** [comment]
Hello @matthdsm, I suggest posting this on one of the forums offered by the cromwell team (They have a slack and a jira board), since this is more about the specifics of how cromwell operates as opposed to how wdl works. You can find out more information over at their github page: https://github.com/broadinstitute/cromwell
