### ISSUE TITLE
use shell variables in output

### ISSUE THREAD

**Issue by Liripo** [openwdl/wdl#453]
```wdl
workflow main {
    String filename="a.test"
    call var {
        input:
            filename=filename
    }
    call write {
    	input:
	    file=var.out
    }
}

task var {
    String filename
    command<<<
	cd /test_wdl
	file=$(pwd)"${filename}"
    >>>
    output {
	String out = "$file"
    }
}
task write {
    String file
    command <<<
	cd /test_wdl
	echo "${file}" >out.test
    >>>
}
```
I would like to ask why the out.test is an empty file.Can't I use shell variables in output

**Comment by illusional** [comment]
Unfortunately you can't use shell variable in the output, and you've designated the output of your task to be `String`, where it probably should be a `File`. My recommendation would be to:

- Declare the output filename in WDL, and pass that through to your command block
- Use a `glob` to collect files with a specific pattern.
