### ISSUE TITLE
Upgrade Current Version to 1.1

### ISSUE THREAD

**Issue by patmagee** [openwdl/wdl#455]
Now that `1.1` is live, we should update the documentation to point to  `1.1` as the current version

**Comment by patmagee** [comment]
We Should verify if 1.1 is live in the relevent engines before promoting:

- miniwdl: @mlin
- cromwell: @cjllanwarne or @vdauwera 
- wdltools: @jdidion

**Comment by pshapiro4broad** [comment]
It is not yet supported in cromwell. See https://github.com/broadinstitute/cromwell/issues/6221 https://broadworkbench.atlassian.net/browse/CROM-6710

**Comment by geoffjentry** [comment]
I think as long as 2 of the 3 have support it's fine to go forward

**Comment by mlin** [comment]
miniwdl supports v1.1 with some errata documented [here](https://miniwdl.readthedocs.io/en/latest/runner_reference.html#wdl-interoperability).

I'd be hesitant to direct users to 1.1 by default without at least a timeline from Cromwell, maybe it's a chicken and egg thing though.

**Comment by patmagee** [comment]
@mlin, I have a rough timelime from the cromwell team. It's not on their immediate radar but it sounds like they are hoping to get to it this year

**Comment by jdidion** [comment]
A great way to demonstrate to the community that WDL != Cromwell would be to not hold up advancing the current version of the spec to 1.1 because Cromwell does not yet support it.

**Comment by jdidion** [comment]
Answering your original question - yes, wdlTools supports 1.1.

I am going to remove the `blocked` label. Anyone please feel free to re-apply it if you really think it's justified to hold this up until all runtimes support 1.1.

**Comment by patmagee** [comment]
@jdidion I think Majority support of the engines should be enough to make the change to documentation. wdlTools (therefore dnanexus), and miniwdl support 1.1. IMO this should be enough to promote 1.1 to be the official "Current" version

**Comment by skchronicles** [comment]
Hey @jdidion @patmagee,

I hope you all are having a great day, and that you're staying safe in these strange times.

I was just wondering if either of you know about know about the current status of Cromwell and its plan support and/or inclusion for WDL/1.1. 

Also, @jdidion I recently saw that DNAnexus is supporting Nextflow. Do you know if DNAnexus has any plans to support Snakemake in the future.

**Comment by patmagee** [comment]
Hello @skchronicles I hope you are keeping safe as well. Unfortunately we are not in the know of when cromwell plans to implement 1.1 (or any other feature forbthe matter). Those decisions are made by their product and development team, based on what their internal needs are.

**Comment by skchronicles** [comment]
@patmagee Sounds good, I wasn't sure if you had any information about a rough timeline from the Cromwell team.
