### ISSUE TITLE
Unify Antlr Parser Directories and Documentation

### ISSUE THREAD

**Issue by patmagee** [openwdl/wdl#456]
In an effort to get more people to use the official grammars we should make a concerted effort to unify the structure of these directories across versions, as well as provide all the necessary documentation needed to get up and running

## Proposed Changes

1. Remove all language specific directories (java, javascript, etc)
2. Update the Readme to include clear instructions on how to generate the grammar for different target languages. 
3. Make sure a readme is in every directory

**Comment by patmagee** [comment]
@jdidion you might find this interesting

**Comment by jdidion** [comment]
I think this is done. It there is anything left to do, please open the issue in the wdl-parsers repo.
