### ISSUE TITLE
CODE chunk passing parameters

### ISSUE THREAD

**Issue by Liripo** [openwdl/wdl#457]
Hello:
This is a working example：
```shell
task test_do {
    String file
    command <<<
        awk '{print $0}' ${file} > a.txt
        R<<CODE
            vroom::vroom("a.txt")
        CODE
    >>>
}
````
I would like to ask if I can use ${file} directly in the CODE chunk.
example:
```shell
task test_do {
    String file
    command <<<
        R<<CODE
            vroom::vroom(${file})
        CODE
    >>>
}
````
or pass ${file} as the parameter of commandArgs() in R

```shell
task test_do {
    String file
    command <<<
        R<<CODE
           args <- commandArgs()
            vroom::vroom(args[1])
        CODE ${file}
    >>> 
}
````

**Comment by patmagee** [comment]
Yes, you can. variable resolution in the task happens prior to the task command being executed. one side note, I would recommend using `wdl version 1.0` if possible and sticking to the `~{file}` command syntaxt. There are a lot of positive things that have happened in v1
