### ISSUE TITLE
how to convert a  comma-delimited or tab-delimited string to an Array

### ISSUE THREAD

**Issue by wonderful1** [openwdl/wdl#463]
hi, i want to convert a String (like "aaa,bbb,ccc") to an  Array： ["aaa","bbb","ccc"], What should I do ?

thank you very much!!

**Comment by illusional** [comment]
My recommendation would be to use a task with python to do it, something like:

```wdl
task SplitString {
  input {
    String str
    String separator
  }
  command {
    python -c 'import json; print(json.dumps("{str}".split("{separator}")))'
  }
  runtime {
    docker: "python:3"
  output {
      Array[String] out = read_json(stdout())
  }
```

NB: this doesn't handle quotes in the str, or separator in this form.

**Comment by patmagee** [comment]
If you have control over whether this is a csv or  tsv you could always try do8ng something  with  engine functions.

I have not tested this, so not sure whether it would work or not. Ultimately it will depend on how the `write_lines` function handles escape characters.

```
  Array[String] lines = ["a\tb\tc"]
  File intermediate_tsv = write_lines(lines)
  Array[Array[String]] split_lines = read_tsv(intermediate_tsv)

```

**Comment by jdidion** [comment]
@patmagee your code should work - it's a nice test case

**Comment by patmagee** [comment]
@wonderful1 if you have any more issues, please feel free to reopen this
