### ISSUE TITLE
using arrays in "if" statements

### ISSUE THREAD

**Issue by matthdsm** [openwdl/wdl#466]
Hi,

I'm trying to do something along the lines of:
```wdl
 Array[File]? qc_results

command {
    ~{if defined(qc_results) then "cp ~{sep=' ' qc_results} ." else ""}
}
```

But I can't find a way to get this to work. What's the correct WDL syntax to achieve this?

Thanks
M

**Comment by rhpvorderman** [comment]
In my opinion Optional lists are evil.

Try it with `Array[File] qc_results = []`. An empty list should evaluate to an empty string with `sep`.

**Comment by matthdsm** [comment]
Thanks,

However, the issue still remains, and empty string would results in a the command `cp .` which would fail.

The actual problem is that WDL doesn't seem to allow the use of the `sep` operator within an `if` statement.

M

**Comment by matthdsm** [comment]
```wdl
 Array[File] qc_results = []

command {
        ~{if length(qc_results) > 0 then "cp " + ~{sep=" ", qc_results} + " ." else ""}
}
```
throws the following error:
```
Unrecognized token on line 453, column 50:

        ~{if length(qc_results) > 0 then "cp " + ~{sep=" ", qc_results} + " ." else ""}
                                                 ^
```

**Comment by rhpvorderman** [comment]
`~{if length(qc_results) > 0 then "cp" else ""} ~{sep=" ", qc_results} ~{if length(qc_results > 0 then "." else ""}`

**Comment by matthdsm** [comment]
Not as concise, but it works!
Thanks!

M
