### ISSUE TITLE
Docker task runtime assumes /bin/bash

### ISSUE THREAD

**Issue by Xophmeister** [openwdl/wdl#467]
[Note: This is probably a Cromwell/implementation issue, rather than being specific to WDL.]

When setting a Docker runtime for a task, the task is assumed to be a Bash script and the container is run with `/bin/bash`. This works fine if `/bin/bash` exists inside the container, but this is not a safe assumption. For example, I just tried to run a Busybox container as the runtime of my task, which failed immediately because `/bin/bash` doesn't exist.

The default should be `/bin/sh`, which is guaranteed by POSIX. Either that, or it should be customisable via a runtime attribute.

**Comment by mlin** [comment]
The spec itself actually does name bash as the command interpreter in a number of places, so it's more than an implementation detail. I think there would be a positive but manageable number of roadbumps involved in relaxing that, for example the exact semantics of `glob()`

**Comment by illusional** [comment]
You can configure this behaviour in Cromwell by adding the following to your config:

```hocon
system: {
  "job-shell": "/bin/sh"
}
```

**Comment by rhpvorderman** [comment]
Might I note that using busybox is **NOT** safe as a bioinformatics container? Some scripts use `wc` for example and some of the busybox commands only operate at 32-bit, meaning they are limited to `2^32 - 1` for their maximum integer count and make a round trip back to `0` when this amount is exceeded.  We have had  issues with this before in our pipelines. @Redmar-van-den-Berg can tell you all about it.

It is much safer to build on top of the `debian:x-slim` container which uses the proper GNU coreutils. That does have /bin/bash by the way.

**Comment by patmagee** [comment]
as @mlin mentioned, the specification is currently very dependant on the existence of `bash` for behaviour around globing. While this is restrictive to an extent, it also simplifies implementation for the engines and provides a consistent experience for the end users (us). I also think there is alot of room for improvement and support of alternative shells, please feel free to [open an RFC](https://github.com/openwdl/wdl/discussions/new) to get the discussion rolling!

Also, given that @illusional did provide a fix for this behaviour in cromwell (which seems to be what you are using), I am going to go ahead and close this for now
