### ISSUE TITLE
RFE: improving WDL workflow task documentation

### ISSUE THREAD

**Issue by aedavids** [openwdl/wdl#471]
Originally submitted to the Terra request for enhancement link. They asked that it be posted here

![image](https://user-images.githubusercontent.com/58153730/124183842-a6d1f480-da6d-11eb-90ff-8d052a33248a.png)

https://p27.zdusercontent.com/attachment/2378360/b3GgSUtddqCtlIwZJsHRQyXsJ?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..vOCzPgdPATlgHUMw5LdwSQ.GC0YjszLDykUDNqPbOdGxjzfOQlM6YFlQFzqENJ_EIGpViShkfi_aV65xKlDvJpsatFkkF7-SDsERrMu8zhF7E08jHf0GnDI1unb7lVv4rV43y1DcOfVyfJkzsrLI_BbpS8x8K51gaYgzgE1g4t1iG--XJlLqMdtWYtMLTqu2I8E7GiJT-enE7zymFv5NoTmVWiL1iQdnADV2ObxZ2lQ6P12ntRW0zgeAYPhb0HSaI6acgYg5mGY7RcHDlDqHVgwP175T1IqMpyQfRlznx68BAa6_hSoNlbyl06_jQYKe-A.L_m5-Z47hcvpooxfYRp6vw

https://p27.zdusercontent.com/attachment/2378360/2dSa3ohYPLa3za3pO2hCULnqf?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..76EXL2sybettbKre8aUFsg.SmT8WtyWF09Iw6UDWUprQdy0Qb6SpquhoRzilz9d2HB-1j6fJLelEVEr-NLK2dwqiHxIoptff0OAHZ38twUd5XkCiAJYfVa8s39Y0Q0zor3dfp9E4N-Mpcj0WDbLz3ASvD6S3595DOX62gJ-HAnJ77elM3_zhOp8l2XlJtdlOSKbzWQjwMqaDAoPeeOnHVPZYybSDA9HSNshHkRQmwaZETgNuxlD03uGYjTSN62rFV0aJaHKTPN9NiCBIOWMLMH5SfOrhpzqTuQr7He66b7wYKpo6908svXHux3kF3ZuhSM.UdTED35IWjjq1IrNGPGGRg

**Comment by jdidion** [comment]
Have a look at [https://github.com/dnanexus-rnd/wdlTools/doc/Commands/Docgen.md](wdlTools docgen). This will generate markdown files from your WDLs that incorporate not only `meta` and `parameter_meta` but also comments.

There are a couple of other documentation systems you might also want to checkout:
* https://github.com/stjudecloud/wdldoc
* https://github.com/biowdl/wdl-aid

**Comment by patmagee** [comment]
Additionally, while we do not officially support multi-line comments, or the concept of a "docstring" (as of yet), you are free to annotate your WDL files with comments to help document them.

I am going to close this for now, pleas feel free to reopen if you do not feel like the links above are sufficient

**Comment by jdidion** [comment]
FWIW, in wdlTools we parse comments by concatenating any block of lines. If you start your comment with two hashes, it is considered a docstring, then it is left as-is. For example:

```wdl
# this is
# a comment
```

becomes "this is a comment" while

```wdl
## this is a docstring
## I am treated as
##     preformatted
```

is left with the line brakes and leading spaces in-tact. This is for the purpose of generating documentation with the `wdlTools doc` command.

**Comment by aedavids** [comment]
Thanks John

Andy

From: John Didion ***@***.***>
Reply-To: openwdl/wdl ***@***.***>
Date: Tuesday, July 20, 2021 at 9:07 AM
To: openwdl/wdl ***@***.***>
Cc: "andrew e. davidson" ***@***.***>, Author ***@***.***>
Subject: Re: [openwdl/wdl] RFE: improving WDL workflow task documentation (#471)


FWIW, in wdlTools we parse comments by concatenating any block of lines. If you start your comment with two hashes, it is considered a docstring, then it is left as-is. For example:

# this is

# a comment

becomes "this is a comment" while

## this is a docstring

## I am treated as

##     preformatted

is left with the line brakes and leading spaces in-tact. This is for the purpose of generating documentation with the wdlTools doc command.
