### ISSUE TITLE
Issue with www.openwdl.org (works without www.)

### ISSUE THREAD

**Issue by kinow** [openwdl/wdl#475]
Might be related to #446 ? And it could be an SSL certificate issue or if using GitHub Pages the CNAME configuration...

![image](https://user-images.githubusercontent.com/304786/130702892-52ac9adf-b984-4b90-ab0a-83faed6358d7.png)

Removing the www. from the URL:

![image](https://user-images.githubusercontent.com/304786/130702975-70b7e03e-b566-4b56-982d-26c3f2698334.png)

Same behavior with Firefox LTS Ubuntu LTS and with Chromium latest, as well as from Wi-fi and from 4G mobile (different networks/DNS/etc).

**Comment by jdidion** [comment]
This appears to be resolved.
