### ISSUE TITLE
Optional boolean and flag in command

### ISSUE THREAD

**Issue by Melkaz** [openwdl/wdl#490]
Hello,

I'm trying to achieve this pattern:

```wdl
version 1.1

task Task {

    input {
        Boolean? showVersion = true
    }

    String versionFlag = if showVersion then '--version' else None

    command {
        head ~{versionFlag}
    }

    output {
        File out = stdout()
    }
}
````

This fails with miniWDL and report this error: `(simple.wdl Ln 9 Col 26) Expected Boolean instead of Boolean?; in if condition`

Is there a way to specify a flag if an optional boolean is set ?

Thank you !

**Comment by rhpvorderman** [comment]
Try

```wdl
version 1.1

task Task {

    input {
        Boolean showVersion = True
    }

    String versionFlag = if showVersion then '--version' else ''

    command {
        head ~{versionFlag}
    }

    output {
        File out = stdout()
    }
}
```
Booleans can only hold two values. `True` or `False`. It is best to set a sane default, and handle the True and False case. Adding another optional case is usually very confusing (for Booleans).

**Comment by Melkaz** [comment]
Thank you for your input.

I found a more elegant solution, but strangely it only works on version 1.0:

```wdl
version 1.0

task Task {

    input {
        Boolean showVersion = true
    }

    # String versionFlag = if showVersion then '--version' else ''

    command {
        head ~{true="--version" false="" showVersion}
        # head ~{versionFlag}
    }

    output {
        File out = stdout()
    }
}
```

Is it by design that this pattern: `~{true="--version" false="" showVersion}` is missing from 1.1 ?

**Comment by patmagee** [comment]
@Melkaz Yes, we removed that pattern and went with the more typical `if ... then ... else` pattern within the interpolation blocks
The following should work for you

```
head ~{if showVersion then "--version" else ""}

```
