### ISSUE TITLE
should read_boolean() convert inputs to lowercase before checking?

### ISSUE THREAD

**Issue by mr-c** [openwdl/wdl#494]
miniWDL does so, but the spec does not specify as such. Can this be allowed in the next version of openwdl?

https://github.com/chanzuckerberg/miniwdl/blob/0ee2bddaea4bd2538cd21bd9b7806a6c81068b2f/WDL/StdLib.py#L104

https://github.com/chanzuckerberg/miniwdl/blob/0ee2bddaea4bd2538cd21bd9b7806a6c81068b2f/WDL/StdLib.py#L326

Draft implementation: https://github.com/openwdl/wdl/tree/494-read-bool

**Comment by patmagee** [comment]
I feel like the intention of that function was definitely to be case insensitive, however this definitely deserves clarification

**Comment by patmagee** [comment]
Honestly, I think the least surprising approach is the best. If it looks like the word "true" regardless of case, then it's true, if it looks like "false" then it's false.

For reference, Java's `Boolean.parseBoolean` function is entirely case insensitive. You can even give it a string like `tRuE` and it will evaluate to `true`

**Comment by jdidion** [comment]
Addressed in 1.1.3
