### ISSUE TITLE
Stdout and Stderr Empty 

### ISSUE THREAD

**Issue by leomoreno310** [openwdl/wdl#496]
Trying to print stdout and stderr to files so that I can see what my command is doing. I broke it down to the simple example shown in the docs. 

```task echo {
  command <<< 
          echo "hello world" 
          echo "another world"
          >&2 echo "hello world"
  >>>
  output {
    File message = stdout()
    File message2 = stderr()
  }
}
```

Both stdout and stderr return empty. My goal is to capture all stdout and stderr from whatever is in the command section. 

On real workflows, I also get a bunch of nonsense in the stdout stderr logs. If my run fails I want to know what caused it.

Using cromwell version 72. Any help?

**Comment by patmagee** [comment]
Hey @leomoreno310 this repository is strictly for the development of the WDL specification, and we do not provide any engine of our own. All engine specific questions should be directed to the appropriate teams in their respective repositories and channels. For this question specifically, I suggest heading over to the [Cromwell teams github repo](https://github.com/broadinstitute/cromwell)
