### ISSUE TITLE
Error while using Directory datatype in wdl

### ISSUE THREAD

**Issue by man4ish** [openwdl/wdl#503]
Hi,

I am trying to read folder as input and for that i am using code below.

**test_dir.wdl** 

       version 1.0
  
       task count
       {
            input
            {
                Directory data_tar
                 String base = basename(data_tar)
            }
           command {
             set -exo pipefail
             echo ${data_tar}
             cp -r ${data_tar} ${base}_folder
         }

         output {
              File Directory = '${base}_folder'
          }

          runtime {
               docker: "docker.io/myname/arc:latest"
         }
    }

    workflow arc{
        input{
            Directory data_tar
        }

       call count{
           input: data_tar=data_tar
         }
      }

**input.json**

       {
            "arc.data_tar": "folder"
       }

**Error while validating:**
        java -jar ~/bin/jar_bundle/womtool-78.jar validate test_dir.wdl 

Failed to process task definition 'count' (reason 1 of 1): No struct definition for 'Directory' found in available structs: []

It seems Directory type does not exist. I tried with version 1.1 but i get error in version line itself.

ERROR: Finished parsing without consuming all tokens.

version 1.1
^

Pls help me how can i use directory?

**Comment by illusional** [comment]
The Directory type is only available in the `development` version of WDL. This should work in Cromwell on most backends.

**Comment by man4ish** [comment]
Ok, but I checked with Cromwell still there is an error. One more thing, with development version you mean that will be released soon?

**Comment by illusional** [comment]
Something like this should work:

```
version development

task star_alignReads {
  input {
    Directory? genomeDir
    ...
```

What sort of errors are you seeing? There's no timeline for the release AFAIK, but it has been supported in Cromwell for over 2 years now.
