### ISSUE TITLE
Is there a GUI application for WDL?

### ISSUE THREAD

**Issue by TrayJames** [openwdl/wdl#505]
Listed on the [Terra website](https://support.terra.bio/hc/en-us/articles/360037493971-Toolkit-All-the-tools-you-need-to-write-and-run-WDLs) in the visualization section Pipeline Builder is listed as a web-based tool for creating WDL workflows. However, it appears to be a dead git repo. Then there is EPAM Cloud Pipelines which appears to be a similar thing to pipeline builder, but I am not sure where to download it. Is there any current WDL GUI applications similar to these two that are available?

**Comment by patmagee** [comment]
@TrayJames there are no tools to to build a gui based WDL workflow as far as I know, in the same way that `Rabix` works for WDL. EPAM used to have a solution, it looks to be more of a complete management interface now at this point (https://github.com/epam/cloud-pipeline)
