### ISSUE TITLE
Scatter over collection caused OutOfMemoryError

### ISSUE THREAD

**Issue by leedchou** [openwdl/wdl#509]
`Scatter` run tasks in parallel, however, if the quantity of input files are over cpu cores, it raised systematic memory issue.
Is there any alternate way that I can run my tasks over these files sequentially like `for` loop?

**Comment by DavyCats** [comment]
This is more of an execution engine implementation detail. In cromwell for example you can set a limit to the number of concurrent jobs: https://cromwell.readthedocs.io/en/stable/backends/Backends/#backend-job-limits
