### ISSUE TITLE
${} ~{}

### ISSUE THREAD

**Issue by yinbinqiu** [openwdl/wdl#511]
Hi
What is the difference between ${} and ~{}？What usage scenarios require special attention?

**Comment by rhpvorderman** [comment]
They have the same function: inserting templated variables into the `command` section. The prefered option now is `~{}`. `${}` used to be the way to insert variables in templates. Unfortunately this is exactly the same to syntax in bash for using environment variables. That made `${}` impractical for some use cases.

```wdl
# OLD SYNTAX:
task hello_world {
    input {
        String user
    }
    command {
         echo Hello, ${user}!
         echo ${STRING}
    }
    # This command will fail since it tries to template the variable 'STRING' which does not exist
}

# NEW SYNTAX:
task example {
    input {
        String user
    }
    command <<<  
         echo Hello, ~{user}!
         echo ${STRING}
    >>>
    # This command will succeed. Please not the usage of '<<<' and '>>>' as delimiters for command.
    # This makes sure the bash environment variable syntax can be used.
}
```
Does this sufficiently answer your question?

**Comment by patmagee** [comment]
@yinbinqiu to add onto what @rhpvorderman said, the `${}` syntax is ONLY usable in the legagy command style `command { }` and will actually error out in the new command style block `command <<< >>>`. As noted, this is because the `${}` collides with the bash variable syntax.

You should aim to use `~{}` in all cases since it is the preferred approach and does not collide with the bash syntax

**Comment by yinbinqiu** [comment]
> @yinbinqiu to add onto what @rhpvorderman said, the `${}` syntax is ONLY usable in the legagy command style `command { }` and will actually error out in the new command style block `command <<< >>>`. As noted, this is because the `${}` collides with the bash variable syntax.
> 
> You should aim to use `~{}` in all cases since it is the preferred approach and does not collide with the bash syntax

Thank you.
