### ISSUE TITLE
Adding naming conversion to the specification document.

### ISSUE THREAD

**Issue by junaruga** [openwdl/wdl#514]
When checking the variables in the language specification. I see these are written as snake case (`foo_bar`). But I see a few variables are written as a camel case (`fooBar`). Today I saw one repository whose WDL files with the variables, and task names are entirely written in camel case. I was shocked. Because I was thinking about reusing some of the parts.

I think it's better to show the recommended naming conversion snake or camel case in the workflow name, task name, variable names and etc as well as other language specifications. What do you think?

E.g. https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#struct-usage

```
workflow workflow_a {
  input {
    Experiment myExperiment
  }
  File firstFile = myExperiment.experimentFiles[0]
  String experimentName = myExperiment.experimentData["name"]
}
```

**Comment by rhpvorderman** [comment]
> I think it's better to show the recommended naming conversion snake or camel case in the workflow name, task name, variable names and etc as well as other language specifications. What do you think?

Having a style guide such as Python's PEP8 will help the WDL ecosystem I think. 

> Today I saw one repository whose WDL files with the variables, and task names are entirely written in camel case. I was shocked. Because I was thinking about reusing some of the parts.

As one of the committers of such repositories, can I ask what is so shocking about camel case that the code cannot be reused?

**Comment by junaruga** [comment]
Yeah, a document like [PEP8](https://pep8.org/) is helpful.

**Comment by jdidion** [comment]
Thanks for pointing this out. I will correct these examples in version 1.1.1.

**Comment by jdidion** [comment]
Updated in [version 1.1.1](https://github.com/openwdl/wdl/tree/version-1.1.1). Please let me know if you find any other such issues.

**Comment by rhpvorderman** [comment]
> Of course, technically I can reuse it. It's just more about the emotional things. Imagine you see a code in Python that the variables are written as camel case.

I can't argue with emotions :wink:. [biowdl tasks](https://github.com/biowdl/tasks) is camel case for various reasons.

- We came from a scala code base (BioPET)
- When we started Cromwell was the de facto exeution engine. Also written in scala.
- We used a scala test framework,

In that light it made sense to follow the scala naming conventions for things. That includes camelCase for variables and CamelCase for "classes" (tasks, workflows etc.). 

I do prefer the Python conventions, Python being the primary language I use. So when WDL comes with a style guide I am all for it following the Python PEP8 style (that seems to be the consensus nowadays anyway). But this can't be changed for biowdl/tasks because that would massively break backwards compatibility.

**Comment by DavyCats** [comment]
Just for reference as well, there are some WDL style guides out there already (two that I'm aware of):
* https://github.com/dnanexus/wdlTools/blob/develop/doc/Style.md
* https://biowdl.github.io/styleGuidelines.html

**Comment by junaruga** [comment]
> Updated in [version 1.1.1](https://github.com/openwdl/wdl/tree/version-1.1.1). Please let me know if you find any other such issues.

Thanks for the work! I checked on the `version-1.1.1` branch.

```
$ git checkout version-1.1.1
```

I found the 2 parts that we need to fix.

https://github.com/openwdl/wdl/blob/version-1.1.1/versions/1.1/SPEC.md#struct-definition
`myString` and `myInt`
```
struct Invalid {
  String myString = "Cannot do this"
  Int myInt
}
```

https://github.com/openwdl/wdl/blob/version-1.1.1/versions/1.1/SPEC.md#string-substring-string-string
`outputFile`

```
File outputFile = output_file_name
```

I checked by the command below.

```
$ grep -E '[a-z][A-Z]' versions/1.1/SPEC.md
```

**Comment by junaruga** [comment]
> We came from a scala code base (BioPET)

I can understand this situation. People who are familiar with the Scala, and Java world, may want to use the language's naming conversions for WDL.

**Comment by junaruga** [comment]
@DavyCats thanks for the references.

> https://biowdl.github.io/styleGuidelines.html - 5. Naming conventions

* Tasks: UpperCamelCase
* Workflows: UpperCamelCase
* Structs: UpperCamelCase
* Calls: lowerCamelCase
* Variables: lowerCamelCase
* Inputs: see the notes below
* Imports: lowerCamelCase

As a reference, here are the [Python PEP8's naming conversions](https://peps.python.org/pep-0008/#descriptive-naming-styles).

I am comfortable with the Workflow Task name as a Camel case. It is like Python.


In the WDL, I see that the attributes are the camel case.
https://github.com/openwdl/wdl/blob/version-1.1.1/versions/1.1/SPEC.md#mandatory-runtime-attributes

* `maxRetries`
* `returnCodes`

**Comment by jdidion** [comment]
Thanks @junaruga I fixed those two examples as well.

Regarding the runtime attributes, I think those were borrowed from Cromwell.
