### ISSUE TITLE
Output folder organization

### ISSUE THREAD

**Issue by choishingwan** [openwdl/wdl#516]
`Array[File]` outputs from a workflow will each be organized in their own file under the `out` directory, but when `Array` is long, this become rather difficult to identify the required file. Would it be possible for us to *flatten* the output so that for example, if we have a script that generate 10 figures, we can still store them in the same folder under `out` instead of having them separated from `00` to `10`?

Thank you

**Comment by rhpvorderman** [comment]
From the context of your comment I take it you are using miniwdl to run your WDL workflows?
There is a `use_relative_output_paths` option but [that was added very recently](https://github.com/chanzuckerberg/miniwdl/pull/608) and is only available on the latest develop branch.

Cromwell has had this feature for a while: https://cromwell.readthedocs.io/en/stable/wf_options/Overview/#output-copying . 

Does this answer your question?

**Comment by choishingwan** [comment]
Yes, that's exactly what I need. Thank you so much!
