### ISSUE TITLE
Allow `~{}` and `${}` literals in strings

### ISSUE THREAD

**Issue by jdidion** [openwdl/wdl#519]
If `~{}` or `${}` appear in a string (optionally with text between the braces), they are parsed as placeholders, and there is currently no way to use an escape sequence to write these as literal values. The easiest solution would be to amend the spec to allow escaping of `{`, so one can write `~\{}` or `$\{}`.

**Comment by patmagee** [comment]
@jdidion inan how nearly surprised that this is not the current behaviour... I would probably categorize this as an oversight, but it should be added as a spec change/clarification imo instead of just errata

**Comment by jdidion** [comment]
I updated the errata and will add it to the 1.1.1 spec.
