### ISSUE TITLE
WDL workflow releases system

### ISSUE THREAD

**Issue by qinqian** [openwdl/wdl#528]
Dear WDL developers, 

Are there any ongoing WDL workflow release system like [nf-core](https://nf-co.re/rnavar) for nextflow or [pypi](https://pypi.org/) for python packages? 

Best,
Alvin

**Comment by DavyCats** [comment]
Perhaps this might be of interest: https://dockstore.org/

There has been some discussion on a formal specifications of WDL packages here: https://github.com/openwdl/wdl/discussions/499 (also relevant: https://miniwdl.readthedocs.io/en/latest/zip.html), and a registry for such packages here: https://github.com/openwdl/wdl/discussions/493. There hasn't been a lot of activity on this though.

**Comment by qinqian** [comment]
Hi Davy, 
Thank you for the quick reply! Dockstore looks good but not an easy way to develop and be imported into existing workflow. I  think something like #493 and #499 would be really helpful for WDL developer. I'd like to be a beta user and contributor if anyone plan to continue this activity. 
Best,
Alvin
