### ISSUE TITLE
Raising an exception within WDL

### ISSUE THREAD

**Issue by microbioticajon** [openwdl/wdl#533]
Hi Guys,

Apologies if this is in the docs andI missed it but is there a way I can raise an exception or simply fail the workflow from within the WDL document?

I have two mutually exclusive optional inputs, one must be set but not both. I want to report back to the user (preferably before the task starts) that this is not allowed.

The ability to raise exceptions or fail a workflow, I think would be useful in general.

Again, apologies if I missed this in the docs.

**Comment by jdidion** [comment]
WDL has no specific error handling/reporting mechanism. One way I have seen it handled for your use case is to have a task that is just for causing the workflow to fail and report an error:

```
workflow Foo {
  if (a and !b) { ... }
  if (b and !a) { ... }
  if (a and b) {
    call fail { input: message = "You must specify 'a' or 'b' but not both" }
  }
}
```

**Comment by microbioticajon** [comment]
Hi @jdidion,

Many thanks for this - I was using an unbalanced zip() to halt execution. The task call idea is cleaner but still a call I would like to avoid before it heads off to the cluster.

I will give it a try!
Thanks,
Jon

**Comment by jdidion** [comment]
Sure - but presumably that's an edge case that won't happen often in practice.
