### ISSUE TITLE
Get length of Map

### ISSUE THREAD

**Issue by SHuang-Broad** [openwdl/wdl#534]
I believe this is an overlooked feature.
Currently `length` only accepts Array.

Draft implementation: https://github.com/openwdl/wdl/tree/534-generalize-length

**Comment by jdidion** [comment]
You're right...we should genericize length.

**Comment by SHuang-Broad** [comment]
Cool! Looking forward to this being implemented.

Just for completeness, in WDL 1.0 I'm able to have a "hack" by coercing the Map to Array[Pair[..., ...]].
