### ISSUE TITLE
How does WDL run only part task of a workflow?

### ISSUE THREAD

**Issue by bioinformzhang** [openwdl/wdl#537]
hi,
This is not about reporting a BUG! I just was very confused and didn't find the answer online!
How does WDL run only part task of a workflow? such as using some options or some special setting
If this feature is not available, I hope it can be added it, because I think it is an important one!

Thank you for giving your soul!

**Comment by rhpvorderman** [comment]
You can use `if` statements to run certain tasks or subworkflows.
Have a look at https://github.com/biowdl/QC/blob/develop/QC.wdl. Here you can see that if there are accomodations for libraries that are not paired end.

**Comment by jdidion** [comment]
Some of the implementations (e.g. miniwdl) also give you the option of running just a specific task.
