### ISSUE TITLE
Runtime access to `requirements` and `hints`

### ISSUE THREAD

**Issue by jdidion** [openwdl/wdl#542]
See #418

**Comment by jdidion** [comment]
To summarize, we would add an implicit variable to every task. I propose to call this variable `task` because that's guaranteed not to clash with any existing variable names, since `task` is a reserved word. Its declaration would be:

```
struct Requirements {
  Array[String]+ container,
  Float cpu,
  Float memory,
  ...
}

struct TaskInfo {
  Requirements requirements,
  Object hints,
  Object meta,
  Object parameter_meta
}

TaskInfo task = TaskInfo { ... }
```

The engine is responsible for populating `task` with the `actual` values for the `Requirements` attributes (which default to the requested values or to the defaults specified in the spec) and a copy of the hints, meta, and parameter_meta in `Object` form. The `task` variable can be accessed in expressions in the command and output sections only.

**Comment by patmagee** [comment]
I like the idea of being able to use the language semantics (Ie structs) to describe new features of the language itself. This feels complete and I think it is a really great approach to providing that information.


One thing that we should think through is how to avoid a race condition where the information in the `TaskInfo` could impact the requirements of the given task. We would probably need to require the `task` key to only be referencable from within string interpolations within the command block OR provide some guidance with how the values should be resolved

Would the `task` keyword be auto populated within a given task and guaranteed to always be available, or does the user need to define the task in the inputs and the engine would "inject" the task info into it?



```wdl
task foo {
  input {
    TaskInfo task 
  }

 command <<< 
    echo ~{task.requirements.cpu}
 >>>
}

## Vs

task foo {
  input {

  }
 
 command <<< 
    echo ~{task.requirements.cpu}
 >>>
}
```

**Comment by patmagee** [comment]
[This](https://github.com/openwdl/wdl/issues/542) discussion raises the question of whether other metadata can be accessed.

1. Task names
2. Call Name
3. Workflow Name
4. Task Id 
5. Workflow Id
6. Parameter meta?

**Comment by jdidion** [comment]
Yes to task name, `meta` and `parameter_meta`, as those are local to the task. I would leave call name, workflow name, etc as optional, although maybe standardize on the field names for engines that choose to provide them.

**Comment by rhpvorderman** [comment]
Task name seems a bit redundant though. What is the use case? And if there is a use case, is it really such a bad cost for a WDL user to type the name twice? Surely, the task will be named after the tool and won't change much? In biowdl/tasks I think we almost never renamed a single task IIRC.

Having access to runtime requirements is quite essential, but I would leave other metadata out for now until there is a clear use case. Every feature we come up is another TODO for the engine developers and I'd rather have to focus on the important bits.

**Comment by patmagee** [comment]
@rhpvorderman i think while the task may be named after the tool, the call could have a different name.

**Comment by rhpvorderman** [comment]
True. Do you have a use case for this?
