### ISSUE TITLE
Repository reorganization

### ISSUE THREAD

**Issue by jdidion** [openwdl/wdl#544]
I think our experience with the current repository structure over the past few years has shown it is less than ideal. It makes new development and releasing new versions too difficult.

This discussion originated on Slack (https://openwdl.slack.com/archives/D010Z3Z2WKV/p1676317994743469).

## Proposed new structure

* The spec lives in the root folder of the repository in `SPEC.md`.
* Other documentation (e.g., the [Implementation Guide](/versions/1.1/ImplementationGuide.md)) moves either to the root folder or a `docs` folder.
* The README provides links to the current and previous releases.
* Things like `highlighters`, `parsers`, parser grammars, etc. should move to their own repository(ies).

## Proposed development process

The WDL specification is versioned using [semver](https://semver.org/).

* A new major spec version is introduced when there are changes to the spec that may break existing workflows, such as the removal of deprecated features or changes to the semantics of existing features.
* A new minor spec version is introduced when new syntax, library functions, or non-breaking semantic changes are added.
* A patch spec version is introduced to make changes that do not introduce any new features or change any existing syntax or semantics, such as fixing typos, adding/improving examples, or making neutral clarifications to ambiguous language (i.e. clarifications that are not counter to any existing implementation and are not likely to break existing workflows).

The WDL *language* is versioned using only major and minor version numbers. A patch spec version will never change the WDL language version.

There is a branch for the current released version of the spec. For example, at the time of this writing, the current version is 1.1, so the branch might be called `wdl-1.1`. When this proposal is implemented, the GitHub project's primary branch will be changed from `main` to `wdl-1.1`, and `main` will be left unchanged so as not to break any external links.

There is a branch for the next minor version of the spec. For example, at the time of this writing, the next minor version is 1.2, so the branch might be called `wdl-1.2`. All changes that are scheduled for inclusion are developed in feature branches off of the version branch.

When a version is released, the primary branch of the GitHub project is simply updated to point to the branch for that version and a new branch is created for the next minor version. For example, when version 1.2 is released, the primary branch of the GitHub project will be updated to `wdl-1.2` and the branch for the previous version will remain unchanged.

Each patch release gets its own branch. When a patch is released, it is merged into the minor version branch. The README is updated to reflect the patch history. Patch releases should be done on regular intervals and include any fixes up to that point. Any outstanding patches to the current version should be applied  before updating to a new version.

There is a branch for the next major version of the spec. For example, at the time of this writing, the next major version is `2.0`, so the branch might be called `wdl-2.0`. The development process is the same as above. Generally, only breaking changes are added to the next major version of the spec. When a new minor version of the spec is released, the branch for the next major version must be rebased to the `HEAD` of the new minor version branch.

Each active major spec version (e.g. `1` and `2`) have their own development branch (e.g. `devel-1` and `devel-2`). The development branch is for unscheduled changes to the spec. Any unscheduled change should be developed in a branch off of the appropriate development branch (depending on whether or not it is a breaking change). These changes are considered experimental until they are accepted into a release version. The purpose of the development spec is for users and runtime developers to experiment with new features in coordination with the community. When a new minor version of the spec is released, the corresponding development branch must be rebased to the `HEAD` of the new minor version branch. When a new major version is released, any differences between the previous development branch and new release branch should be migrated to the development branch of the new major version, and a new development branch should be created for the next major version.

**Comment by jdidion** [comment]
Here is what the new structure would look like: https://github.com/openwdl/wdl/tree/wdl-1.1

**Comment by patmagee** [comment]
Thank you so much for setting this up @jdidion. Overall I really like this proposal. The current structure has continued to grow in complexity and made things like backporting fixes very challenging.

This proposal seems relatively similar to the release model that a language like [kotlin](https://github.com/JetBrains/kotlin) uses. 

The main difference though is constantly changing the main branch to point to the most recent version of the language spec. I am not sure I am a fan of that approch, but i can definitely see why we would do that.

Maybe we can try to answer the following questions that will help guide the best approach

1. When a PR is made against the repo proposing a change, is it made against the next version development branch, the main branch or the last release branch?
1. Does merging a PR imply acceptance of a feature into the next release?
1. What branch / version of the spec will breaking changes be made against?

**Comment by patmagee** [comment]
Another example repo to look at which strictly uses tagged releases is [Rust](https://github.com/rust-lang/rust). I think both rust and kotlin provide a good paradigm for how to version a language

**Comment by jdidion** [comment]
1. If the change is for a scheduled feature (ie the gov team has approved it) then it is PR'd against the next minor version branch if it is non-breaking, or the next major version branch if it is breaking.
2. Only if it is merged into a version branch. Unscheduled features are PR'd agains the devel branch for the appropriate major version (depending on if the change is breaking or not).
3. The next major version branch (if scheduled) or devel branch (if not).

**Comment by illusional** [comment]
As long as we make old versions of the spec easy to find (eg: links to latest, v1.0, v1.1), or maybe we should host the spec on the openwdl website, then I'm for this.

**Comment by jdidion** [comment]
Yes, previous versions of the spec would be linked from the README in the current version of the spec. The motivation of leaving the `main` branch in-tact is to avoid breaking any existing links to the spec from external websites.

**Comment by jdidion** [comment]
This was discussed on the 5/24 governance call and everyone who attended was in support. @patmagee @cjllanwarne @aednichols @geoffjentry (I don't have Venkat's github handle) feel free to confirm with a 👍.
