### ISSUE TITLE
cromwell-85.jar don't support WDL version 1.1

### ISSUE THREAD

**Issue by chenyuxing1197296672** [openwdl/wdl#546]
I am a Chinese, please ignore my poor presentation skills. I write a simple script, include the following,
```wdl
version 1.1
task hello {
  input {
    File infile
    String pattern
  }

  command <<<
    egrep '~{pattern}' '~{infile}'
  >>>

  runtime {
    container: "my_image:latest"
  }

  output {
    Array[String] matches = read_lines(stdout())
  }
}

workflow wf {
  input {
    File infile
    String pattern
  }

  call hello {
    input: infile, pattern
  }

  output {
    Array[String] matches = hello.matches
  }
}
``` 
The above code comes from this link ‘https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md‘, i just add a header 'version 1.1' at the top, but when i validate the code , the following error occurred. please help me , thank you

![微信截图_20230328092810](https://user-images.githubusercontent.com/37786769/228104564-5c3061d3-00b1-4320-bab3-dc39bcbbd29e.png)

**Comment by rhpvorderman** [comment]
Cromwell does not support 1.1 yet.

@chenyuxing1197296672 It looks like your workflow will do fine with version 1.0. Or you could use [miniwdl](https://github.com/chanzuckerberg/miniwdl).

**Comment by chenyuxing1197296672** [comment]
> Cromwell does not support 1.1 yet.
> 
> @chenyuxing1197296672 It looks like your workflow will do fine with version 1.0. Or you could use [miniwdl](https://github.com/chanzuckerberg/miniwdl).
It's really helpful, it worked,  best wishes for you, thank you

**Comment by rhpvorderman** [comment]
Thanks for reporting back!
