### ISSUE TITLE
miniwdl engine with version 1.1/development can not find local data

### ISSUE THREAD

**Issue by chenyuxing1197296672** [openwdl/wdl#549]
Please forgive my poor expression, I wrote a WDL script, the container is a required, but my data is stored locally. when i run the script, the stderr reports they can't find file,like this:
![image](https://user-images.githubusercontent.com/37786769/229398132-68a83f73-40c6-45cd-b6bd-f660a72b405f.png)
Detailed info:
            1.  I use miniwdl and version 1.1/development
            2. My local data localized in /home/chenyuxing, the two files are following and i grant all permission to those files to keep them from they can't be read.
            ![image](https://user-images.githubusercontent.com/37786769/229397315-e36fcd2d-6428-4dd9-a7d8-896c6decaf6d.png)
At present,i had tried following methods, 
             I mounted the local directory to container and used the docker's path, like /ngs/xxx.file, but it's not useful
![image](https://user-images.githubusercontent.com/37786769/229398466-cc0084e1-d631-4c85-b0db-219a968a7607.png).
Can you give me some suggestion.

**Comment by rhpvorderman** [comment]
Container is not required on 1.0 or 1.1 so you can simply leave it out. Cromwell should run the job locally.

**Comment by chenyuxing1197296672** [comment]
> Container is not required on 1.0 or 1.1 so you can simply leave it out. Cromwell should run the job locally.

Dear Sir, I am very happy to see you again. Version 1.1 also requires the use of containers, Version 1.0 is not required, but I need to use the function of gpu acceleration, so I am unwilling to give up version 1.1 or the development version. can you tell me how you usually deal with this problem. thank you.

**Comment by chenyuxing1197296672** [comment]
oh sorry, everyone, this error occured only due to my stupid, i have resolved this problem, thank you
