### ISSUE TITLE
Bring sanity to the Spec situation

### ISSUE THREAD

**Issue by geoffjentry** [openwdl/wdl#55]
(@kcibul - another [Jeff Special](https://github.com/broadinstitute/cromwell/issues/778))

The status of our spec(s) is super confusing.

There's "Draft 1 (closed)" which predates our team. There's "Draft 2 (open)". There's the master branch. There's the develop branch. The "Draft 2" on master doesn't match what's in develop all the time. There's also only one _real_ implementation of the spec, and it's not even complete.

I recognizing the desire on our past selves' part to be official about everything but we could simplify this a _lot_ by just having _a spec_ that's allowed to change at will until if/when it actually becomes a problem.

**Comment by vdauwera** [comment]
Oh god yes please

(And if you can break it down into sections rather than a monolithic doc, all the better)

**Comment by geoffjentry** [comment]
@vdauwera Note the issue over in Cromwell which I tagged you in ;)

**Comment by geoffjentry** [comment]
This is exactly what openwdl was designed to take care of, closing to remove clutter
