### ISSUE TITLE
Outdated link on openwdl.org

### ISSUE THREAD

**Issue by kayleemathews** [openwdl/wdl#561]
In the section, **More Information**, on the openwdl.org website, the link for **Quick start and tutorials** is outdated. The link should be updated to https://wdl-docs.readthedocs.io/en/latest/.

**Comment by patmagee** [comment]
Thanks @kayleemathews.

One thing I wonder is whether we should consider making the docs website the landing page of the openwdl.org website (if possible).

We can make the home page a blurb about what wdl is, as opposed to having the very very outdated website that we have

**Comment by patmagee** [comment]
@kayleemathews so let's keep status quo for now, but what I DID do is add a DNS CNAME record pointing https://docs.openwdl.org to the doc site!

**Comment by zkamvar** [comment]
Hello, I wanted to read some documentation and noticed that the openwdl.org domain is down: https://downforeveryoneorjustme.com/openwdl.org?proto=https.

The last snapshot appears to be https://web.archive.org/web/20230530171416/https://openwdl.org/

**Comment by geoffjentry** [comment]
Hi @zkamvar - this is a known issue, brought up on slack: https://openwdl.slack.com/archives/CT0QEK1V0/p1694549874273229
