### ISSUE TITLE
How to specify a parameter of task in a imported sub-workflow

### ISSUE THREAD

**Issue by zqHealth** [openwdl/wdl#569]
I found the parameters of imported task can by specified in the JSON config file, though they are not the input variables of the workflow.
But parameters of a task of imported sub-workflow cannot.

e.g.
I want to specify the 'cpu' parameter of a task, which is in a sub-workflow imported by the main-workflow. 
The 'cpu' parameter is not a input variable in the sub-workflow or in the main-workflow. 

 ---

-  part of the main-workflow WDL code:

```
import "../task/NormalizeGWASResult.wdl" as SigleNormalizeGWASResult  # import sub-workflow
...
call SigleNormalizeGWASResult.NormalizeGWASResult as BasedataQC1 { ... }
```

- part of the sub-workflow WDL code:
```
task FilterAndStandardizeGWASFile {
    input {
        ...
        Int cpu = 1
    }
    ...
}

workflow NormalizeGWASResult {
    input {}
    call FilterAndStandardizeGWASFile {..}
}
```

-  part of the JSON config file
"PRSAnalysis.BasedataQC1.FilterAndStandardizeGWASFile.cpu": 4

 --------
Here is the part of the Error message:

WorkflowManagerActor: Workflow 057b380f-7a12-4356-bb7d-ed993b1cbb7e failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
WARNING: Unexpected input provided: PRSAnalysis.BasedataQC1.FilterAndStandardizeGWASFile.cpu (expected inputs: [PRSAnalysis.sampleListFile, ............

**Comment by DavyCats** [comment]
You might have to add this to your workflow:
```wdl
  meta {
    allowNestedInputs: true
  }
```
https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#computing-call-inputs

**Comment by zqHealth** [comment]
Thank you Davy, that's what I need :)
