### ISSUE TITLE
Handling of Array[Array[File]?]?

### ISSUE THREAD

**Issue by rdemolgen** [openwdl/wdl#570]
I have a workflow with various scatter gathers and end up with an `Array[Array[File]?]?`.  I pass this to a task where I would like to convert to `Array[File]` so that I can use `~{sep=" " <files>}`

I know I need to convert it from an optional array and flatten the array by using `select_all()` and `flatten()` but I get several errors.

When I try:
`Array[Array[File]?]? optional_array`
`Array[Array[File]] non_optional_array = select_all(optional_array)`
I get the following error:
`IdentifierLookup(optional_array)'. Expected an array of optional values (eg 'Array[X?]') but got 'Array[Array[File]?]?'`

When I try to flatten the array:
`Array[Array[File]?]? optional_array`
`Array[File] flattened_array = flatten(optional_array)`
`Invalid parameter 'IdentifierLookup(optional_array)'. Expected 'Array[Array[_]]' but got 'Array[Array[File]?]?'`

So I'm just not sure how to get `Array[Array[File]?]?` to `Array[File]` since `select_all()` and `flatten()` don't seem to like `Array[Array[File]?]?`

Do you have any suggestions?

Thanks

**Comment by pshapiro4broad** [comment]
This is confusing (and the error messages aren't much help) but I think you can use `select_first()` to make this work. Your type `Array[Array[File]?]?` has two optionals. One is at the top level; to remove that you can use `select_first([optional_array])`. Once that's done you now have the type `Array[Array[File]?]`, so now you can use `select_all()`. This code passes `miniwdl check` but I didn't try making a running example:

```wdl
version 1.0

workflow W {
input {
  Array[Array[File]?]? optional_array
}

  Array[Array[File]?] non_optional_array1 = select_first([optional_array, [[]]]) 
  Array[Array[File]] non_optional_array = select_all(non_optional_array1)
}
```

Also in general, GitHub Issues are not a good place for a support question like this, unless you think you've found a bug. I would instead post to the openwdl slack or mailing list. https://github.com/openwdl/wdl#community-and-support
