### ISSUE TITLE
How to set environment in wdl on server cluster?  

### ISSUE THREAD

**Issue by FionaMoon** [openwdl/wdl#582]
Hi All,
My workflow needs 2 tools that are not compatible with one Python environment. So I create 2 conda environments on the server cluster. Our server cluster doesn't support docker.
I want to set 2 tasks for my workflow like this
```
## conda activate Python3.6
## conda activate Python3.9
task Python3.6 {
      ...
	}
task Python3.9 {
      ...
	}
```
Does anyone know how to change the environment in WDL?

Thank you in advance!

**Comment by DavyCats** [comment]
You could activate the conda environment inside of the command section:
```wdl
task py6 {
  command {
    set -e
    source /path/to/conda/install/bin/activate py6
    ...
  }
}

You might also want to have a look at apptainer/singularity, udocker or podman. These are all programs capable of running docker images without root access and are therefore often usable on clusters.
