### ISSUE TITLE
How to use local file as input?

### ISSUE THREAD

**Issue by FionaMoon** [openwdl/wdl#584]
Hi All,
I am new to wdl and I met same problems when using local files as input.
I use absolute path in JSON
```
{
"MitochondriaPipeline.atac_aligned_input_bam": "/public/home/WDL/output/test-ATAC-seq/raw_bam/SRR23984614_So.bam"
}
```
However, when I call the path in the command line, the output is not my absolute path.
```
# command
echo -e "*****\n~{input_bam}"
# output
# echo -e "*****\n/public/home/WDL/output/test-ATAC-seq/cromwell-executions/MitochondriaPipeline/6aa997fd-ad0d-4671-bdd1-030ed5c517ae/call-CallFileName/inputs/-1304302568/SRR23984614_So.bam"
```
What should I do to get my absolute path?

Thank you in advance!

**Comment by nshrine** [comment]
I don't think you can, I think WDL is designed to run in environments where the input files are pulled in to locations that are only defined at runtime... but I may be talking rubbish because I'm new to WDL too, but I ran into the same problem and that's what I concluded.

**Comment by patmagee** [comment]
@FionaMoon when you are running workflows locally using MiniWDL or Cromwell, you can in fact pass lock files as inputs to the engine.

Specifying the the file in the way you have done when suppling the inputs to the engine typically should work

Within a given task things are a bit different then what you might expect. When you pass the engine the file, it is responsible for ensuring that the file is accessible to your task, with the given base file name, but not necessarily at the same path.

Why does it do this? A few reasons really

1. To avoid collisions when using distributed systems with inputs coming from buckets or urls.
2. Often tasks use docker or some other container environment, so the path that is available on your local machine is not available within the container
3. To have more control over the execution environment

**Comment by FionaMoon** [comment]
Thank you!
Now I can run wdl with local file.
