### ISSUE TITLE
function to grab file extension

### ISSUE THREAD

**Issue by besh-t** [openwdl/wdl#590]
Hi there, it would be great to have a function in the WDL standard library to grab the extension without having to do multiple string manipulations in the code. Thanks.

**Comment by jdidion** [comment]
In WDL 1.2 we will add the `find` function, which will enable you to search for a specific string/regexp within another string (https://github.com/openwdl/wdl/issues/133).

We are also considering adding a `split` function, which would enable you to split a string on a specific delimiter (https://github.com/openwdl/wdl/issues/553).

A current work-around for this if you want to test whether a file has a certain extension is:

I think one or both of these would enable you to do what you want, but please re-open if you have a use case that is not covered.

```
if (basename(my_file, ".txt") != basename(my_file)) { ... }
```

**Comment by besh-t** [comment]
Thanks for the update. Will do.

Besher
