### ISSUE TITLE
Getting workflow inputs

### ISSUE THREAD

**Issue by mbestipa** [openwdl/wdl#599]
Hi there.
I'm trying to validate the wdl input file for a workflow using a custom python/pydantic module. Stuff like, the input string has to conform to some regexp. (I realize this example could be done with wdl, but I would like to abstract it away so that I can also pass it around in different python projects)
Is there any way to get a json file of all the inputs of the workflow? Something like `worfklow_name.inputs`

Right now it seems like you would need to take all of the individual inputs of the workflow in a new task, create an object and write them to a file, and then passing the resulting file into the validation module

**Comment by patmagee** [comment]
WDL itself does not have any facilities for this, but tools like [MiniWDL](https://github.com/chanzuckerberg/miniwdl) would allow you to extract all of the information you need.

Essentially you need to parse the workflow using some sort of parser and extract the inputs from that
