### ISSUE TITLE
Wrong paths for WDL 1.1 example tests

### ISSUE THREAD

**Issue by stxue1** [openwdl/wdl#652]
The path `/greetings.txt` probably shouldn't be an absolute path, and `greetings2.txt` does not exist in the [data directory](https://github.com/openwdl/wdl/tree/fc24d91a11355ffb74961704ea255f74986f7913/tests/data)

https://github.com/openwdl/wdl/blob/fc24d91a11355ffb74961704ea255f74986f7913/SPEC.md?plain=1#L362

It's causing some issues running the [wdl-tests](https://github.com/openwdl/wdl-tests) framework

**Comment by jdidion** [comment]
Thanks, should be fixed now
