### ISSUE TITLE
Are workflow declarations optional?

### ISSUE THREAD

**Issue by stxue1** [openwdl/wdl#655]
I haven't seen anything in the WDL 1.1 spec about whether the workflow declaration is optional, but some of the examples that the [wdl-tests repo](https://github.com/openwdl/wdl-tests) depends on seem to assume that they should be optional. Does somewhere in the spec say they are optional? Or is it just assumed that workflow declarations are optional? If so, should this be added to the spec?

For example, this snippet does not specify a workflow:
https://github.com/openwdl/wdl/blob/9c0b9cf4586508a9e6260cc5c5e562e21f625aac/SPEC.md?plain=1#L4226-L4244

**Comment by jdidion** [comment]
https://github.com/openwdl/wdl/blob/wdl-1.1/SPEC.md#wdl-documents

If that's not clear enough, please feel free to submit a PR with suggested clarification.

**Comment by stxue1** [comment]
Thanks, I think it is clear, just a little hard to find. It would be nice if there was some reference in the workflow/task definition sections, but including it twice may be redundant.
