### ISSUE TITLE
Introduce enum syntax

### ISSUE THREAD

**Issue by patmagee** [openwdl/wdl#658]
A long standing request from users has been the ability to define enum constants where a user can restrict the values an input can contain and easily refer to those values in a named way. While restricting the values is accomplishable with validation (see #657), being able to easily refer to those constants is another matter.

At the risk of making WDL a little bit more like a programming language, I propose we add a new construct called `enum`

```wdl
enum Foo {
  FOO
  BAR
  BIZ
}


workflow my_workflow {
  input {
    Foo val
  }

  if (Foo.BAR == val) {
    call bar
  }

}
```

**Semantics:**

- Input values are provided as JSON strings, where the String value is expected to equal the value of the enum
- The strings are case sensitive (`"Foo"` != `FOO`)
- A String can be converted to an enum `Foo foo = "FOO"`

**Comment by jdidion** [comment]
Duplicate of https://github.com/openwdl/wdl/issues/139?

**Comment by patmagee** [comment]
Huh, yup. This is what happens when you do not look at the history @jdidion

**Comment by patmagee** [comment]
closing in favour of #139
