### ISSUE TITLE
RFE:  would be nice to have richer, regex()-like file search (beyond just glob)

### ISSUE THREAD

**Issue by noblem** [openwdl/wdl#90]
In issue #89 I mentioned a use case of wanting to get a list of 3 kinds of files in a directory 

*.png
*.txt
*.html

and store this list into a single output variable.  The glob() function is not expressive enough to generate such a list with a single call, but a regular expression-based function would be.

**Comment by jdidion** [comment]
You should be able to do this: `flatten([glob("*.png"), glob("*.txt"), glob("*.html")])`.
