### ISSUE TITLE
RFE:  make shell script generated to execute command section less fragile

### ISSUE THREAD

**Issue by noblem** [openwdl/wdl#91]
Consider a WDL command section with 2 or more Unix statements.  Cromwell currently reports that such commands "succeed" even when one or more of its Unix statements fail (i.e. return a non-zero status code), as long as the final statement returns a zero status code (e.g. echo "Done").  

This is fragile, and I think it's far more common to want Cromwell to report a failure in such cases than to silently ignore them.   

One workaround is to chain all statements together into one effective line, using && to separate each statement, but this is less flexible and readable (uglier).  To make it easier for the common case to be more robust and readable, it would be helpful to consider having the generated *script* file begin with "set -eo pipefail" (maybe even 'set -euo pipefail')

**Comment by patmagee** [comment]
@geoffjentry @orodeh out of curiosity, has this been fixed in your implementations? Additionally, do you think this is something that should be defined in the specification as an enforced implementation detail? If not we should close this as implementation detail and not a language specification

**Comment by orodeh** [comment]
Perhaps I don't understand, but can't the user simply add the line `set -eo pipefail` to the beginning of the command section?

**Comment by patmagee** [comment]
@orodeh thats my thinking. that this is not necessarily something we want to enforce as a specification. If we are agreed on that We can close this issue
