### ISSUE TITLE
RFE:  basic introspection would be nice, easy to add feature

### ISSUE THREAD

**Issue by noblem** [openwdl/wdl#96]
It is useful to have files created by tasks/workflows reflect the name of the thing that created them, like
```
task Foo {
     command {
             echo "blah blah blah" > Foo_output.txt
              ...
     }
     ...
}
```
But right now this name has to be hardcoded into the WDL.  It would be cleaner and more robust (e.g. to changes in the workflow or task name) if it could instead be referenced by introspection, such as ${\_\_name\_\_} or something.  Rather than duplicating the task name as a hardcode in multiple places within the various sections of the WDL body.

**Comment by patmagee** [comment]
The user can specify the name of a file based on an input string, giving them complete and dynamic control over naming already. Static names are only such if you write the task in that way
